/**
 * Day 2 Study Guide — Anonymous Credentials + TEEs
 * Data file loaded by the study plan website.
 */

window.DAY2_GUIDE = {
  block1: {
    title: "Anonymous Credentials (CL, BBS+, VCs)",
    connectionsSummary:
      "Anonymous credentials are the CORE of your thesis. BBS+ is the leading candidate for credential signatures on Sui \u2014 it is pairing-based (same curves as Groth16), supports efficient selective disclosure, and is being standardized by W3C. Understanding CL vs BBS+ tradeoffs is essential for your design choices.",
    concepts: [
      {
        name: "Anonymous Credentials",
        analogy:
          "A bouncer at a club who can verify you are over 21 without seeing your name, address, or photo. You prove a property about yourself without revealing your identity. The bouncer never learns who you are, only that you meet the entry requirement.",
        diagram: [
          "┌────────┐  issue  ┌──────┐  present",
          "│ Issuer │───────→│ User │─────────→",
          "└────────┘  cred  └──────┘  ZK proof",
          "    │                │",
          "    │  signs all     │  holds full",
          "    │  attributes    │  credential",
          "    │                │          ┌──────────┐",
          "    │                └─────────→│ Verifier │",
          "    │                           └──────────┘",
          "    │                sees only disclosed attrs",
          "    │                                │",
          "    └── CANNOT track usage ──────────┘",
        ].join("\n"),
        keyPoints: [
          "Unlinkability: issuer cannot track where or when you use your credential",
          "Selective disclosure: reveal only the attributes needed for each interaction",
          "Minimal disclosure principle: never share more than strictly required",
          "Multi-show unlinkability: using the same credential twice appears as two different users",
        ],
        connections:
          "Your thesis builds an anonymous credential system on Sui. Users receive credentials (e.g., KYC-verified, accredited investor) and prove properties without revealing identity, enabling private payments and compliant DeFi.",
      },
      {
        name: "CL Signatures (Camenisch-Lysyanskaya)",
        analogy:
          "A magic stamp that can be broken into pieces. The stamp proves the whole document is valid, but you can show just one piece (one attribute) without revealing the rest. The catch: the stamp is large and heavy (RSA-based, big keys).",
        diagram: [
          "CL Multi-Message Signature",
          "┌────────────────────────────┐",
          "│ msg = (m1, m2, m3, m4, m5) │",
          "│ sig = Sign(sk, m1..m5)     │",
          "└─────────────┬──────────────┘",
          "              │ selective disclosure",
          "              ▼",
          "┌────────────────────────────┐",
          "│ Reveal: m1, m3             │",
          "│ Hidden: m2, m4, m5 (ZK)   │",
          "│                            │",
          "│ Verifier checks sig valid  │",
          "│ over ALL 5, sees only 2    │",
          "└────────────────────────────┘",
        ].join("\n"),
        keyPoints: [
          "Multi-message signing: one signature covers multiple attributes simultaneously",
          "Attribute-based credentials: each message slot encodes one user attribute",
          "RSA-based: large key sizes (~2048 bits), slower than pairing-based schemes",
          "Efficient for selective disclosure but less compact than BBS+",
          "Foundation of IBM Idemix (Identity Mixer) system",
        ],
        connections:
          "CL signatures were the first practical anonymous credential scheme. Understanding CL helps you appreciate why BBS+ is preferred for Sui: CL keys are too large for on-chain storage and verification is expensive in circuits.",
      },
      {
        name: "BBS+ Signatures",
        analogy:
          "A holographic badge with hidden layers. The full badge contains all your info, but you can activate specific layers while keeping others invisible. Unlike the heavy CL stamp, this badge is lightweight and becoming the industry standard.",
        diagram: [
          "┌────────┐ sign  ┌──────────────┐",
          "│ Issuer │──────→│ BBS+ Sig     │",
          "│(sk,pk) │       │ (m1..m5)     │",
          "└────────┘       └──────┬───────┘",
          "                 derive │ proof",
          "                       ▼",
          "              ┌────────────────┐",
          "  Shown: m1,m3│ ZK Proof of   │",
          "  Hide: m2,m4 │ sig on ALL    │",
          "         m5   │ messages      │",
          "              └───────┬────────┘",
          "                verify│",
          "                      ▼",
          "              ┌────────────────┐",
          "              │ Verifier (pk)  │",
          "              │ Accept/Reject  │",
          "              └────────────────┘",
        ].join("\n"),
        keyPoints: [
          "Pairing-based cryptography: bilinear pairings on elliptic curves (BLS12-381)",
          "Unlinkable proofs: two presentations of the same credential cannot be linked",
          "Compact: smaller keys and signatures than CL (~48-96 bytes per group element)",
          "W3C standardization candidate for Verifiable Credentials Data Integrity",
          "Proof of knowledge of signature without revealing the signature itself",
        ],
        connections:
          "BBS+ is the primary candidate for your thesis credential system. It uses the same pairing-friendly curves as Groth16 (BLS12-381), making it efficient to verify BBS+ signature proofs inside SNARKs on Sui.",
      },
      {
        name: "Selective Disclosure",
        analogy:
          "A redacted document at a government hearing. You show the relevant paragraphs and black out the rest, but the official stamp on the page still proves the entire original document was authentic and unmodified.",
        diagram: [
          "Full Credential    Selective Proof",
          "┌──────────────┐  ┌──────────────┐",
          "│ name: Alice  │  │ name: ██████ │",
          "│ age:  25     │→ │ age>18: YES  │",
          "│ city: Zurich │  │ city: Zurich │",
          "│ id:   CH-123 │  │ id:   ██████ │",
          "│ role: student│  │ role: ██████ │",
          "└──────────────┘  └──────────────┘",
          " sig: valid        ZK proof that:",
          "                   - sig is valid",
          "                   - hidden attrs",
          "                     exist & match",
          "                   - age >= 18",
        ].join("\n"),
        keyPoints: [
          "Prove predicates (age > 18) without revealing the exact value",
          "Range proofs: demonstrate a value falls within a range without disclosure",
          "Attribute equality: prove same attribute across two credentials without revealing it",
          "Combine multiple credentials in a single presentation",
          "Foundation for privacy-preserving identity verification",
        ],
        connections:
          "Selective disclosure is the key feature for your thesis use cases. A user can prove 'I am KYC-verified and accredited' to a DeFi protocol on Sui without revealing their name, nationality, or any other personal data.",
      },
      {
        name: "W3C Verifiable Credentials & DIDs",
        analogy:
          "A digital passport system where YOU hold your documents in your own wallet, not in a government database. You choose what to share with each service. No central authority can revoke your ability to present credentials or track where you use them.",
        diagram: [
          "┌──────────┐ resolve ┌───────────┐",
          "│   DID    │←───────│    DID    │",
          "│ Registry │        │  Document │",
          "└──────────┘        └───────────┘",
          "     ▲             pk, service│",
          "     │                        │",
          "┌────┴─────┐ issue  ┌────┴────┐",
          "│  Issuer  │──────→│ Holder  │",
          "└──────────┘       └────┬────┘",
          "                  VP   │",
          "               (subset of VCs)",
          "                       ▼",
          "               ┌────────────┐",
          "               │  Verifier  │",
          "               │ checks:    │",
          "               │ -DID sig   │",
          "               │ -VC valid  │",
          "               │ -VP proof  │",
          "               └────────────┘",
        ].join("\n"),
        keyPoints: [
          "Self-sovereign identity: users control their own credentials without intermediaries",
          "DID methods: did:web, did:key, did:sui (potential) map identifiers to public keys",
          "JSON-LD vs JWT: two serialization formats for VCs with different tradeoffs",
          "Holder-controlled presentation: user decides what to share and with whom",
          "Interoperability: standard format enables cross-platform credential exchange",
        ],
        connections:
          "Your thesis maps the VC/DID model onto Sui. DIDs could be Sui addresses, VCs are issued off-chain (or anchored on-chain), and VPs are ZK proofs verified by Sui smart contracts. This bridges W3C standards with blockchain verification.",
      },
      {
        name: "Revocation Mechanisms",
        analogy:
          "A 'banned users' list that does not reveal who is on it. To use your credential, you prove 'I am NOT on this list' without showing which entry you checked. The list can be updated without reissuing credentials to honest users.",
        diagram: [
          "Accumulator-Based Revocation",
          "┌──────────────────────────────┐",
          "│      Accumulator (acc)       │",
          "│ acc = g^(s+id1)(s+id2)..     │",
          "└──────────────┬───────────────┘",
          "     ┌─────────┼─────────┐",
          "     ▼         ▼         ▼",
          "  ┌─────┐  ┌─────┐  ┌─────┐",
          "  │ id1 │  │ id2 │  │ id3 │",
          "  │(ok) │  │(rev)│  │(ok) │",
          "  └──┬──┘  └─────┘  └──┬──┘",
          "     │                  │",
          "     ▼                  ▼",
          "  witness1          witness3",
          "  proves             proves",
          "  membership         membership",
        ].join("\n"),
        keyPoints: [
          "Accumulator-based: compact cryptographic structure for set membership proofs",
          "Non-membership proofs: prove your ID is NOT in the revoked set",
          "Privacy-preserving: revocation check does not reveal which credential is being checked",
          "Credential validity periods: time-based expiry as a complementary mechanism",
          "Dynamic accumulators allow adding/removing members without reissuing all witnesses",
        ],
        connections:
          "On Sui, the revocation accumulator can be stored as a shared object, updated by the issuer. Users fetch the latest accumulator and generate a non-membership proof as part of their credential presentation ZK circuit.",
      },
    ],
  },
  block2: {
    title: "TEEs (SGX, Attestation, Trust Model)",
    connectionsSummary:
      "TEEs complement ZKPs in your thesis architecture. While ZKPs provide trustless verification, TEEs can accelerate proving time and enable private computation that would be too expensive in pure ZK. Your thesis explores using TEEs as an efficiency layer while maintaining ZKP as the trust anchor.",
    concepts: [
      {
        name: "Trusted Execution Environments (TEE)",
        analogy:
          "A transparent vault inside your computer. Code runs inside where NOBODY (not even the OS or hardware owner) can see or tamper with the data. The vault has a window showing results but not internals. Even the datacenter operator with physical access cannot peek inside.",
        diagram: [
          "┌──────────────────────────────┐",
          "│       Application            │",
          "├──────────────────────────────┤",
          "│     Operating System         │",
          "├──────────────────────────────┤",
          "│       Hypervisor             │",
          "├─────────┬────────────────────┤",
          "│Hardware │ ┌────────────────┐ │",
          "│         │ │  TEE Enclave   │ │",
          "│         │ │ ┌────────────┐ │ │",
          "│         │ │ │ Protected  │ │ │",
          "│         │ │ │ Code+Data  │ │ │",
          "│         │ │ └────────────┘ │ │",
          "│         │ │ Isolated from  │ │",
          "│         │ │ ALL above      │ │",
          "│         │ └────────────────┘ │",
          "└─────────┴────────────────────┘",
        ].join("\n"),
        keyPoints: [
          "Hardware-based isolation: CPU enforces memory encryption and access control",
          "Confidentiality: data inside the TEE is encrypted even in RAM",
          "Integrity: any tampering with enclave code or data is detected",
          "Defense in depth: protects against compromised OS, hypervisor, and physical attacks",
          "Attestation: TEE can prove to remote parties what code it is running",
        ],
        connections:
          "In your thesis, TEEs can run credential issuance or ZK proof generation in a protected environment. This enables a hybrid trust model where TEE handles performance-critical operations while ZKPs provide the mathematical guarantee.",
      },
      {
        name: "Intel SGX Enclaves",
        analogy:
          "A diplomatic embassy inside a foreign country. The embassy (enclave) operates under its own rules, and the host country (OS) cannot enter or spy on it, even though it physically surrounds it. Communication happens only through official channels (ECALL/OCALL).",
        diagram: [
          "┌────────────────────────────┐",
          "│ Untrusted Application      │",
          "│ ┌────────────────────────┐ │",
          "│ │ ECALL ──→ Enclave     │ │",
          "│ │          ┌──────────┐  │ │",
          "│ │          │Encrypted │  │ │",
          "│ │          │ Memory   │  │ │",
          "│ │          │ (EPC)    │  │ │",
          "│ │          └──────────┘  │ │",
          "│ │ OCALL ←── Enclave     │ │",
          "│ └────────────────────────┘ │",
          "└────────────────────────────┘",
          "┌────────────────────────────┐",
          "│ Sealed Storage             │",
          "│ (encrypted to enclave key) │",
          "└────────────────────────────┘",
        ].join("\n"),
        keyPoints: [
          "Per-process enclaves: each application creates its own isolated enclave",
          "EPC (Enclave Page Cache): hardware-encrypted memory region, limited to ~128MB",
          "ECALL/OCALL interface: structured entry/exit points between trusted and untrusted code",
          "Sealing: encrypt data to a key derived from enclave identity for persistent storage",
          "Memory Encryption Engine (MEE): encrypts all data leaving the CPU to DRAM",
        ],
        connections:
          "SGX enclaves can host a credential issuer or a ZK prover on Sui validators. The enclave ensures that secret keys (issuer signing key, user private data) never leave the protected environment, even if the host machine is compromised.",
      },
      {
        name: "Remote Attestation",
        analogy:
          "A doctor credential verification before sharing your medical records. You verify the doctor identity, their hospital legitimacy, and that their computer is secure. The TEE proves: 'I am running exactly this code, on genuine Intel hardware, completely untampered.'",
        diagram: [
          "┌──────────┐        ┌────────────┐",
          "│ Enclave  │ quote  │Attestation │",
          "│          │───────→│ Service    │",
          "│MRENCLAVE │        │(IAS/DCAP)  │",
          "│MRSIGNER  │        └─────┬──────┘",
          "└──────────┘        verify│report",
          "                         ▼",
          "                ┌──────────────┐",
          "                │   Verifier   │",
          "                │ Checks:      │",
          "                │ - HW genuine │",
          "                │ - Code hash  │",
          "                │ - Not revoked│",
          "                └──────────────┘",
        ].join("\n"),
        keyPoints: [
          "MRENCLAVE: hash of enclave code and initial data (identity of WHAT is running)",
          "MRSIGNER: hash of the enclave signer key (identity of WHO built it)",
          "Quote generation: enclave produces a signed statement of its measurements",
          "IAS (Intel Attestation Service): centralized verification by Intel",
          "DCAP (Data Center Attestation Primitives): decentralized verification without calling Intel",
        ],
        connections:
          "Remote attestation is critical for your thesis trust model. A Sui smart contract (or off-chain verifier) can verify that a TEE-based credential issuer is running the correct code, bridging hardware trust guarantees into the blockchain protocol.",
      },
      {
        name: "Side-Channel Attacks",
        analogy:
          "Cracking a safe by listening to the clicks. Even though you cannot see inside the TEE, you can observe timing, power consumption, or cache behavior to leak secrets. The vault walls are strong, but information leaks through vibrations.",
        diagram: [
          "┌────────────────────────┐",
          "│     TEE Enclave        │",
          "│  ┌────────────────┐    │",
          "│  │  Secret Data   │    │",
          "│  └────────────────┘    │",
          "└──────────┬─────────────┘",
          "           │ side channels",
          "   ┌───────┼───────┬──────┐",
          "   ▼       ▼       ▼      ▼",
          " Timing  Cache  Spectre Power",
          " Attack  Attack Meltdown Anal.",
          "   │       │       │      │",
          "   │    L1/L2   Specul.   │",
          "   │    probe   Exec.     │",
          "   ▼       ▼       ▼      ▼",
          "┌──────────────────────────┐",
          "│ Leaked bits of secrets   │",
          "└──────────────────────────┘",
        ].join("\n"),
        keyPoints: [
          "Spectre/Meltdown: speculative execution attacks that bypass memory isolation",
          "Cache timing attacks: infer secret data by measuring cache hit/miss patterns",
          "Foreshadow (L1TF): reads SGX-protected memory via L1 cache side channel",
          "Mitigations: ORAM (oblivious RAM), constant-time code, cache partitioning",
          "Residual risk: new side channels are discovered regularly, no complete fix exists",
        ],
        connections:
          "Side-channel risk is why your thesis does not rely on TEEs alone. The hybrid architecture uses ZKPs as the trust anchor (math-based, no side channels) and TEEs as a performance optimization. If the TEE is compromised, the ZKP layer still guarantees correctness.",
      },
      {
        name: "Trust Model: TEE vs ZKP",
        analogy:
          "TEE is trusting a bank vault (hardware manufacturer guarantee). ZKP is trusting math itself (no hardware trust needed). Combining both is belt AND suspenders: if the vault is cracked, the math still holds. If the math is too slow, the vault accelerates it.",
        diagram: [
          "┌─────────────┬───────┬────────┐",
          "│             │  TEE  │  ZKP   │",
          "├─────────────┼───────┼────────┤",
          "│ Trust basis │HW mfg │ Math   │",
          "│ Speed       │ Fast  │ Slow   │",
          "│ Side-chan.  │ Risk  │ Immune │",
          "│ Verify cost │ Low   │ Low(*) │",
          "│ Setup trust │ Intel │CRS/SRS │",
          "└─────────────┴───────┴────────┘",
          "(*) on-chain SNARK verification",
          "",
          "Hybrid Architecture:",
          "┌─────┐ fast path ┌─────┐",
          "│ TEE │──────────→│ Sui │",
          "└──┬──┘           └──┬──┘",
          "   │ fallback        │verify",
          "   ▼                 ▼",
          "┌─────┐          ┌───────┐",
          "│ ZKP │─────────→│ proof │",
          "└─────┘ trust    └───────┘",
          "        anchor",
        ].join("\n"),
        keyPoints: [
          "TEE trusts hardware vendor (Intel/AMD): security depends on manufacturing integrity",
          "ZKP trusts mathematical hardness assumptions: no hardware dependency",
          "TEE is fast but vulnerable to side-channel and physical attacks",
          "ZKP is slow (proving takes seconds-minutes) but provides trustless verification",
          "Hybrid approach: TEE for speed, ZKP as fallback trust anchor when TEE is insufficient",
        ],
        connections:
          "This is the central architectural insight of your thesis. On Sui, TEEs accelerate credential issuance and proof generation while ZKP circuits provide the on-chain verification. If a TEE is compromised, users can fall back to pure ZK proofs, maintaining the system security guarantees.",
      },
    ],
  },
};
