/**
 * Day 2 Study Guide — Anonymous Credentials + TEEs
 * Data file loaded by the study plan website.
 */

window.DAY2_GUIDE = {
  block1: {
    title: "Anonymous Credentials (CL, BBS+, VCs)",
    connectionsSummary:
      "Anonymous credentials are the CORE of your thesis. BBS+ is the leading candidate for credential signatures on Sui \u2014 it is pairing-based (same curves as Groth16), supports efficient selective disclosure, and is being standardized by W3C. Understanding CL vs BBS+ tradeoffs is essential for your design choices.",
    concepts: [
      {
        name: "Anonymous Credentials",
        analogy:
          "A bouncer at a club who can verify you are over 21 without seeing your name, address, or photo. You prove a property about yourself without revealing your identity. The bouncer never learns who you are, only that you meet the entry requirement.",
        diagram: [
          "┌────────┐  issue  ┌──────┐  present",
          "│ Issuer │───────→│ User │─────────→",
          "└────────┘  cred  └──────┘  ZK proof",
          "    │                │",
          "    │  signs all     │  holds full",
          "    │  attributes    │  credential",
          "    │                │          ┌──────────┐",
          "    │                └─────────→│ Verifier │",
          "    │                           └──────────┘",
          "    │                sees only disclosed attrs",
          "    │                                │",
          "    └── CANNOT track usage ──────────┘",
        ].join("\n"),
        keyPoints: [
          "Unlinkability: issuer cannot track where or when you use your credential",
          "Selective disclosure: reveal only the attributes needed for each interaction",
          "Minimal disclosure principle: never share more than strictly required",
          "Multi-show unlinkability: using the same credential twice appears as two different users",
        ],
        publicPrivate: [
          { item: "Issuer secret key (isk)", status: "private", holder: "Issuer", when: "Always" },
          { item: "Issuer public key (ipk)", status: "public", holder: "Everyone", when: "Always" },
          { item: "User attributes (a1,...,aL)", status: "private", holder: "User", when: "Before presentation" },
          { item: "Credential signature (σ)", status: "private", holder: "User", when: "Always (never revealed directly)" },
          { item: "Disclosed attributes", status: "revealed", holder: "Verifier", when: "During presentation (user chooses which)" },
          { item: "Hidden attributes", status: "private", holder: "User", when: "During presentation (not disclosed)" },
          { item: "ZK proof (π)", status: "public", holder: "Verifier", when: "During presentation" },
          { item: "Proof validity result", status: "public", holder: "Verifier", when: "After verification (accept/reject)" },
        ],
        connections:
          "Your thesis builds an anonymous credential system on Sui. Users receive credentials (e.g., KYC-verified, accredited investor) and prove properties without revealing identity, enabling private payments and compliant DeFi.",
        thesisExample:
          "In your thesis, anonymous credentials are the bridge between identity and privacy on Sui. A government issues a credential containing (name, age, nationality, KYC_level) signed with BBS+. When the user wants to make a private payment, they present a zero-knowledge proof that they hold a valid credential with KYC_level >= 2 — the Sui verifier learns only this fact, not the user's identity. The same credential works at different merchants without creating a traceable profile.",
      },
      {
        name: "CL Signatures (Camenisch-Lysyanskaya)",
        analogy:
          "A magic stamp that can be broken into pieces. The stamp proves the whole document is valid, but you can show just one piece (one attribute) without revealing the rest. The catch: the stamp is large and heavy (RSA-based, big keys).",
        diagram: [
          "CL Multi-Message Signature",
          "┌────────────────────────────┐",
          "│ msg = (m1, m2, m3, m4, m5) │",
          "│ sig = Sign(sk, m1..m5)     │",
          "└─────────────┬──────────────┘",
          "              │ selective disclosure",
          "              ▼",
          "┌────────────────────────────┐",
          "│ Reveal: m1, m3             │",
          "│ Hidden: m2, m4, m5 (ZK)   │",
          "│                            │",
          "│ Verifier checks sig valid  │",
          "│ over ALL 5, sees only 2    │",
          "└────────────────────────────┘",
        ].join("\n"),
        keyPoints: [
          "Multi-message signing: one signature covers multiple attributes simultaneously",
          "Attribute-based credentials: each message slot encodes one user attribute",
          "RSA-based: large key sizes (~2048 bits), slower than pairing-based schemes",
          "Efficient for selective disclosure but less compact than BBS+",
          "Foundation of IBM Idemix (Identity Mixer) system",
        ],
        publicPrivate: [
          { item: "RSA modulus (n)", status: "public", holder: "Everyone", when: "Always (part of public key)" },
          { item: "RSA factors (p, q)", status: "private", holder: "Issuer", when: "Always (factoring n is hard)" },
          { item: "Bases S, Z, R_i", status: "public", holder: "Everyone", when: "Always (system parameters)" },
          { item: "Signature (A, e, v)", status: "private", holder: "User", when: "Always (user holds credential)" },
          { item: "Randomized signature (A', v')", status: "public", holder: "Verifier", when: "During proof (unlinkable from original)" },
          { item: "Revealed attributes (m_i, i in D)", status: "revealed", holder: "Verifier", when: "During proof (user chooses D)" },
          { item: "Hidden attributes (m_i, i not in D)", status: "private", holder: "User", when: "During proof (ZK committed)" },
        ],
        connections:
          "CL signatures were the first practical anonymous credential scheme. Understanding CL helps you appreciate why BBS+ is preferred for Sui: CL keys are too large for on-chain storage and verification is expensive in circuits.",
        thesisExample:
          "CL signatures were the original anonymous credential scheme (IBM's Idemix). For your thesis comparison, CL uses RSA groups (~256B keys, slow modular exponentiation) while BBS+ uses pairings (~48B keys, faster operations). Your thesis argues for BBS+ over CL: BBS+ is 5x faster for selective disclosure, has smaller proofs, and aligns with BLS12-381 already used by Sui — making on-chain verification significantly cheaper.",
      },
      {
        name: "BBS+ Signatures",
        analogy:
          "A holographic badge with hidden layers. The full badge contains all your info, but you can activate specific layers while keeping others invisible. Unlike the heavy CL stamp, this badge is lightweight and becoming the industry standard.",
        diagram: [
          "┌────────┐ sign  ┌──────────────┐",
          "│ Issuer │──────→│ BBS+ Sig     │",
          "│(sk,pk) │       │ (m1..m5)     │",
          "└────────┘       └──────┬───────┘",
          "                 derive │ proof",
          "                       ▼",
          "              ┌────────────────┐",
          "  Shown: m1,m3│ ZK Proof of   │",
          "  Hide: m2,m4 │ sig on ALL    │",
          "         m5   │ messages      │",
          "              └───────┬────────┘",
          "                verify│",
          "                      ▼",
          "              ┌────────────────┐",
          "              │ Verifier (pk)  │",
          "              │ Accept/Reject  │",
          "              └────────────────┘",
        ].join("\n"),
        keyPoints: [
          "Pairing-based cryptography: bilinear pairings on elliptic curves (BLS12-381)",
          "Unlinkable proofs: two presentations of the same credential cannot be linked",
          "Compact: smaller keys and signatures than CL (~48-96 bytes per group element)",
          "W3C standardization candidate for Verifiable Credentials Data Integrity",
          "Proof of knowledge of signature without revealing the signature itself",
        ],
        publicPrivate: [
          { item: "Issuer secret key (x, y1,...,yL)", status: "private", holder: "Issuer", when: "Always" },
          { item: "Issuer public key ([x]_2, [y_i]_2)", status: "public", holder: "Everyone", when: "Always (on BLS12-381 G2)" },
          { item: "Signature (A, e, s)", status: "private", holder: "User", when: "Always (user holds credential)" },
          { item: "Randomized A' = A^r1", status: "public", holder: "Verifier", when: "During proof (blinded)" },
          { item: "Blinding factor (r1)", status: "private", holder: "User", when: "Chosen fresh each presentation (enables unlinkability)" },
          { item: "Disclosed attributes", status: "revealed", holder: "Verifier", when: "During proof (user selects which)" },
          { item: "Hidden attributes", status: "private", holder: "User", when: "During proof (ZK committed)" },
        ],
        connections:
          "BBS+ is the primary candidate for your thesis credential system. It uses the same pairing-friendly curves as Groth16 (BLS12-381), making it efficient to verify BBS+ signature proofs inside SNARKs on Sui.",
        thesisExample:
          "BBS+ is THE signature scheme for your credential layer. The issuer signs attributes (a1,...,a10) with one BBS+ signature. During payment on Sui, the user randomizes the signature (A' = A^r) making each presentation unlinkable, then proves in zero-knowledge that specific attributes satisfy the verifier's policy. The pairing equation e(A', X~) = e(A_bar, g~_2) is what your Groth16 circuit encodes for on-chain verification.",
      },
      {
        name: "Selective Disclosure",
        analogy:
          "A redacted document at a government hearing. You show the relevant paragraphs and black out the rest, but the official stamp on the page still proves the entire original document was authentic and unmodified.",
        diagram: [
          "Full Credential    Selective Proof",
          "┌──────────────┐  ┌──────────────┐",
          "│ name: Alice  │  │ name: ██████ │",
          "│ age:  25     │→ │ age>18: YES  │",
          "│ city: Zurich │  │ city: Zurich │",
          "│ id:   CH-123 │  │ id:   ██████ │",
          "│ role: student│  │ role: ██████ │",
          "└──────────────┘  └──────────────┘",
          " sig: valid        ZK proof that:",
          "                   - sig is valid",
          "                   - hidden attrs",
          "                     exist & match",
          "                   - age >= 18",
        ].join("\n"),
        keyPoints: [
          "Prove predicates (age > 18) without revealing the exact value",
          "Range proofs: demonstrate a value falls within a range without disclosure",
          "Attribute equality: prove same attribute across two credentials without revealing it",
          "Combine multiple credentials in a single presentation",
          "Foundation for privacy-preserving identity verification",
        ],
        publicPrivate: [
          { item: "Full credential", status: "private", holder: "User", when: "Always (stored in wallet)" },
          { item: "Disclosed set D", status: "public", holder: "User + Verifier", when: "Agreed before presentation" },
          { item: "Attributes {a_i}_{i in D}", status: "revealed", holder: "Verifier", when: "During presentation (user chosen)" },
          { item: "Attributes {a_i}_{i not in D}", status: "private", holder: "User", when: "During presentation (ZK hidden)" },
          { item: "ZK proof (π)", status: "public", holder: "Verifier", when: "During presentation" },
          { item: "Predicate result (e.g., age >= 18)", status: "public", holder: "Verifier", when: "During presentation (boolean only)" },
          { item: "Exact attribute value behind predicate", status: "private", holder: "User", when: "Always (only predicate result revealed)" },
        ],
        connections:
          "Selective disclosure is the key feature for your thesis use cases. A user can prove 'I am KYC-verified and accredited' to a DeFi protocol on Sui without revealing their name, nationality, or any other personal data.",
        thesisExample:
          "Selective disclosure is the UX differentiator of your system. A user with credential (name, age=25, country=CH, KYC=3) can prove 'age >= 18 AND country in EU/CH' to a Sui DeFi protocol without revealing their exact age (25), name, or KYC level. For payments below the threshold, they only prove 'valid credential exists.' This flexibility means one credential covers convenience stores, DeFi protocols, and regulated exchanges with different disclosure levels.",
      },
      {
        name: "W3C Verifiable Credentials & DIDs",
        analogy:
          "A digital passport system where YOU hold your documents in your own wallet, not in a government database. You choose what to share with each service. No central authority can revoke your ability to present credentials or track where you use them.",
        diagram: [
          "┌──────────┐ resolve ┌───────────┐",
          "│   DID    │←───────│    DID    │",
          "│ Registry │        │  Document │",
          "└──────────┘        └───────────┘",
          "     ▲             pk, service│",
          "     │                        │",
          "┌────┴─────┐ issue  ┌────┴────┐",
          "│  Issuer  │──────→│ Holder  │",
          "└──────────┘       └────┬────┘",
          "                  VP   │",
          "               (subset of VCs)",
          "                       ▼",
          "               ┌────────────┐",
          "               │  Verifier  │",
          "               │ checks:    │",
          "               │ -DID sig   │",
          "               │ -VC valid  │",
          "               │ -VP proof  │",
          "               └────────────┘",
        ].join("\n"),
        keyPoints: [
          "Self-sovereign identity: users control their own credentials without intermediaries",
          "DID methods: did:web, did:key, did:sui (potential) map identifiers to public keys",
          "JSON-LD vs JWT: two serialization formats for VCs with different tradeoffs",
          "Holder-controlled presentation: user decides what to share and with whom",
          "Interoperability: standard format enables cross-platform credential exchange",
        ],
        publicPrivate: [
          { item: "DID", status: "public", holder: "Everyone", when: "Always (on-chain or resolvable)" },
          { item: "DID Document (public keys, services)", status: "public", holder: "Everyone", when: "Always (resolved from DID)" },
          { item: "Verifiable Credential (VC)", status: "private", holder: "Holder", when: "Always (stored in holder wallet)" },
          { item: "Verifiable Presentation (VP)", status: "public", holder: "Verifier", when: "During verification (sent by holder)" },
          { item: "Claims included in VP", status: "revealed", holder: "Verifier", when: "During presentation (holder chooses subset)" },
          { item: "Issuer signature on VC", status: "public", holder: "Verifier", when: "During presentation (in VP)" },
          { item: "Holder private key", status: "private", holder: "Holder", when: "Always (signs presentations)" },
        ],
        connections:
          "Your thesis maps the VC/DID model onto Sui. DIDs could be Sui addresses, VCs are issued off-chain (or anchored on-chain), and VPs are ZK proofs verified by Sui smart contracts. This bridges W3C standards with blockchain verification.",
        thesisExample:
          "Your system implements W3C Verifiable Credentials on Sui. Each user has a DID (did:sui:<wallet_object_id>) resolved from a Sui object. Credentials follow the VC data model with BBS+ as the proof mechanism. The VP (Verifiable Presentation) sent to a Sui smart contract contains the selective disclosure proof. This standards compliance means your thesis system could interoperate with the EU Digital Identity Wallet (eIDAS 2.0) — a massive real-world adoption vector.",
      },
      {
        name: "Revocation Mechanisms",
        analogy:
          "A 'banned users' list that does not reveal who is on it. To use your credential, you prove 'I am NOT on this list' without showing which entry you checked. The list can be updated without reissuing credentials to honest users.",
        diagram: [
          "Accumulator-Based Revocation",
          "┌──────────────────────────────┐",
          "│      Accumulator (acc)       │",
          "│ acc = g^(s+id1)(s+id2)..     │",
          "└──────────────┬───────────────┘",
          "     ┌─────────┼─────────┐",
          "     ▼         ▼         ▼",
          "  ┌─────┐  ┌─────┐  ┌─────┐",
          "  │ id1 │  │ id2 │  │ id3 │",
          "  │(ok) │  │(rev)│  │(ok) │",
          "  └──┬──┘  └─────┘  └──┬──┘",
          "     │                  │",
          "     ▼                  ▼",
          "  witness1          witness3",
          "  proves             proves",
          "  membership         membership",
        ].join("\n"),
        keyPoints: [
          "Accumulator-based: compact cryptographic structure for set membership proofs",
          "Non-membership proofs: prove your ID is NOT in the revoked set",
          "Privacy-preserving: revocation check does not reveal which credential is being checked",
          "Credential validity periods: time-based expiry as a complementary mechanism",
          "Dynamic accumulators allow adding/removing members without reissuing all witnesses",
        ],
        publicPrivate: [
          { item: "Accumulator value (acc)", status: "public", holder: "Everyone", when: "Always (on-chain)" },
          { item: "Full revocation list", status: "private", holder: "Issuer", when: "Depends on scheme (private in accumulator-based)" },
          { item: "Membership witness (w_i)", status: "private", holder: "Each user (their own)", when: "Always (per-user secret)" },
          { item: "Non-revocation proof", status: "public", holder: "Verifier", when: "During credential presentation" },
          { item: "Which credential was checked", status: "private", holder: "User", when: "During proof (unlinkable)" },
        ],
        connections:
          "On Sui, the revocation accumulator can be stored as a shared object, updated by the issuer. Users fetch the latest accumulator and generate a non-membership proof as part of their credential presentation ZK circuit.",
        thesisExample:
          "Your thesis uses an on-chain RSA accumulator for revocation. When an issuer revokes a credential (e.g., expired passport), they update the accumulator on Sui. During each payment, the user includes a non-revocation proof: 'my credential is NOT in the revoked set.' This proof is bundled into the Groth16 circuit alongside the credential proof — one on-chain verification covers both validity and non-revocation, keeping gas costs constant.",
      },
    ],
  },
  block2: {
    title: "TEEs (SGX, Attestation, Trust Model)",
    connectionsSummary:
      "TEEs complement ZKPs in your thesis architecture. While ZKPs provide trustless verification, TEEs can accelerate proving time and enable private computation that would be too expensive in pure ZK. Your thesis explores using TEEs as an efficiency layer while maintaining ZKP as the trust anchor.",
    concepts: [
      {
        name: "Trusted Execution Environments (TEE)",
        analogy:
          "A transparent vault inside your computer. Code runs inside where NOBODY (not even the OS or hardware owner) can see or tamper with the data. The vault has a window showing results but not internals. Even the datacenter operator with physical access cannot peek inside.",
        diagram: [
          "┌──────────────────────────────┐",
          "│       Application            │",
          "├──────────────────────────────┤",
          "│     Operating System         │",
          "├──────────────────────────────┤",
          "│       Hypervisor             │",
          "├─────────┬────────────────────┤",
          "│Hardware │ ┌────────────────┐ │",
          "│         │ │  TEE Enclave   │ │",
          "│         │ │ ┌────────────┐ │ │",
          "│         │ │ │ Protected  │ │ │",
          "│         │ │ │ Code+Data  │ │ │",
          "│         │ │ └────────────┘ │ │",
          "│         │ │ Isolated from  │ │",
          "│         │ │ ALL above      │ │",
          "│         │ └────────────────┘ │",
          "└─────────┴────────────────────┘",
        ].join("\n"),
        keyPoints: [
          "Hardware-based isolation: CPU enforces memory encryption and access control",
          "Confidentiality: data inside the TEE is encrypted even in RAM",
          "Integrity: any tampering with enclave code or data is detected",
          "Defense in depth: protects against compromised OS, hypervisor, and physical attacks",
          "Attestation: TEE can prove to remote parties what code it is running",
        ],
        publicPrivate: [
          { item: "Code running inside TEE", status: "private", holder: "TEE enclave", when: "Always (confidential execution)" },
          { item: "Input data inside TEE", status: "private", holder: "TEE enclave", when: "Always (encrypted in memory)" },
          { item: "Output of TEE computation", status: "public", holder: "Requesting party", when: "After computation (sent to caller)" },
          { item: "TEE internal state", status: "private", holder: "TEE enclave", when: "Always (OS/hypervisor cannot see)" },
          { item: "TEE code hash (measurement)", status: "public", holder: "Everyone", when: "Via attestation report" },
        ],
        connections:
          "In your thesis, TEEs can run credential issuance or ZK proof generation in a protected environment. This enables a hybrid trust model where TEE handles performance-critical operations while ZKPs provide the mathematical guarantee.",
        thesisExample:
          "In your thesis, TEEs provide the fast path for credential verification. When low latency matters (point-of-sale payments), the merchant's TEE verifies the BBS+ credential in ~1ms instead of waiting for on-chain ZKP verification (~500ms proof generation + block time). The TEE guarantees the merchant's software honestly checks the credential without seeing the hidden attributes — hardware-enforced privacy at payment-terminal speed.",
      },
      {
        name: "Intel SGX Enclaves",
        analogy:
          "A diplomatic embassy inside a foreign country. The embassy (enclave) operates under its own rules, and the host country (OS) cannot enter or spy on it, even though it physically surrounds it. Communication happens only through official channels (ECALL/OCALL).",
        diagram: [
          "┌────────────────────────────┐",
          "│ Untrusted Application      │",
          "│ ┌────────────────────────┐ │",
          "│ │ ECALL ──→ Enclave     │ │",
          "│ │          ┌──────────┐  │ │",
          "│ │          │Encrypted │  │ │",
          "│ │          │ Memory   │  │ │",
          "│ │          │ (EPC)    │  │ │",
          "│ │          └──────────┘  │ │",
          "│ │ OCALL ←── Enclave     │ │",
          "│ └────────────────────────┘ │",
          "└────────────────────────────┘",
          "┌────────────────────────────┐",
          "│ Sealed Storage             │",
          "│ (encrypted to enclave key) │",
          "└────────────────────────────┘",
        ].join("\n"),
        keyPoints: [
          "Per-process enclaves: each application creates its own isolated enclave",
          "EPC (Enclave Page Cache): hardware-encrypted memory region, limited to ~128MB",
          "ECALL/OCALL interface: structured entry/exit points between trusted and untrusted code",
          "Sealing: encrypt data to a key derived from enclave identity for persistent storage",
          "Memory Encryption Engine (MEE): encrypts all data leaving the CPU to DRAM",
        ],
        publicPrivate: [
          { item: "MRENCLAVE (code hash)", status: "public", holder: "Everyone", when: "In attestation report" },
          { item: "MRSIGNER (developer identity)", status: "public", holder: "Everyone", when: "In attestation report" },
          { item: "Enclave internal state", status: "private", holder: "Enclave", when: "Always (hardware-encrypted)" },
          { item: "Sealed data", status: "private", holder: "Enclave", when: "Always (encrypted with CPU-derived key)" },
          { item: "EPC memory contents", status: "private", holder: "Enclave", when: "Always (encrypted from OS)" },
          { item: "ECALL parameters", status: "public", holder: "Depends on design", when: "Visible to untrusted app unless encrypted by caller" },
        ],
        connections:
          "SGX enclaves can host a credential issuer or a ZK prover on Sui validators. The enclave ensures that secret keys (issuer signing key, user private data) never leave the protected environment, even if the host machine is compromised.",
        thesisExample:
          "Your TEE layer uses SGX enclaves on Sui validator nodes or payment processors. The enclave loads the BBS+ verification logic and issuer public keys, sealed to MRENCLAVE. Users submit encrypted credential presentations to the enclave via ECALL. The enclave verifies the BBS+ proof, checks the policy, and returns only accept/reject — the credential attributes never leave the encrypted enclave memory, even if the validator node's OS is compromised.",
      },
      {
        name: "Remote Attestation",
        analogy:
          "A doctor credential verification before sharing your medical records. You verify the doctor identity, their hospital legitimacy, and that their computer is secure. The TEE proves: 'I am running exactly this code, on genuine Intel hardware, completely untampered.'",
        diagram: [
          "┌──────────┐        ┌────────────┐",
          "│ Enclave  │ quote  │Attestation │",
          "│          │───────→│ Service    │",
          "│MRENCLAVE │        │(IAS/DCAP)  │",
          "│MRSIGNER  │        └─────┬──────┘",
          "└──────────┘        verify│report",
          "                         ▼",
          "                ┌──────────────┐",
          "                │   Verifier   │",
          "                │ Checks:      │",
          "                │ - HW genuine │",
          "                │ - Code hash  │",
          "                │ - Not revoked│",
          "                └──────────────┘",
        ].join("\n"),
        keyPoints: [
          "MRENCLAVE: hash of enclave code and initial data (identity of WHAT is running)",
          "MRSIGNER: hash of the enclave signer key (identity of WHO built it)",
          "Quote generation: enclave produces a signed statement of its measurements",
          "IAS (Intel Attestation Service): centralized verification by Intel",
          "DCAP (Data Center Attestation Primitives): decentralized verification without calling Intel",
        ],
        publicPrivate: [
          { item: "Attestation report", status: "public", holder: "Verifier", when: "Sent during attestation" },
          { item: "QUOTE", status: "public", holder: "Verifier", when: "Sent during attestation" },
          { item: "Enclave measurement (in report)", status: "public", holder: "Verifier", when: "Embedded in attestation report" },
          { item: "User report data (64 bytes)", status: "public", holder: "Verifier", when: "Included in attestation report" },
          { item: "Intel signing key", status: "private", holder: "Intel", when: "Always (used to sign IAS reports)" },
          { item: "Quote signing key", status: "private", holder: "Platform", when: "Always (hardware-embedded)" },
          { item: "Platform identity (EPID)", status: "private", holder: "Platform", when: "EPID scheme (group signature hides individual)" },
          { item: "Platform identity (DCAP)", status: "public", holder: "Verifier", when: "DCAP scheme (ECDSA reveals platform cert)" },
        ],
        connections:
          "Remote attestation is critical for your thesis trust model. A Sui smart contract (or off-chain verifier) can verify that a TEE-based credential issuer is running the correct code, bridging hardware trust guarantees into the blockchain protocol.",
        thesisExample:
          "Before sending their credential to a TEE, the user verifies via remote attestation that the enclave is running the correct verification code (MRENCLAVE matches the audited binary). The attestation report includes a fresh nonce from the user, preventing replay. On Sui, the attestation could be verified on-chain once, and subsequent users trust the attested enclave — amortizing the attestation cost across many credential verifications.",
      },
      {
        name: "Side-Channel Attacks",
        analogy:
          "Cracking a safe by listening to the clicks. Even though you cannot see inside the TEE, you can observe timing, power consumption, or cache behavior to leak secrets. The vault walls are strong, but information leaks through vibrations.",
        diagram: [
          "┌────────────────────────┐",
          "│     TEE Enclave        │",
          "│  ┌────────────────┐    │",
          "│  │  Secret Data   │    │",
          "│  └────────────────┘    │",
          "└──────────┬─────────────┘",
          "           │ side channels",
          "   ┌───────┼───────┬──────┐",
          "   ▼       ▼       ▼      ▼",
          " Timing  Cache  Spectre Power",
          " Attack  Attack Meltdown Anal.",
          "   │       │       │      │",
          "   │    L1/L2   Specul.   │",
          "   │    probe   Exec.     │",
          "   ▼       ▼       ▼      ▼",
          "┌──────────────────────────┐",
          "│ Leaked bits of secrets   │",
          "└──────────────────────────┘",
        ].join("\n"),
        keyPoints: [
          "Spectre/Meltdown: speculative execution attacks that bypass memory isolation",
          "Cache timing attacks: infer secret data by measuring cache hit/miss patterns",
          "Foreshadow (L1TF): reads SGX-protected memory via L1 cache side channel",
          "Mitigations: ORAM (oblivious RAM), constant-time code, cache partitioning",
          "Residual risk: new side channels are discovered regularly, no complete fix exists",
        ],
        publicPrivate: [
          { item: "Timing information", status: "public", holder: "Attacker", when: "Observable from outside enclave" },
          { item: "Cache access patterns", status: "public", holder: "Attacker", when: "Observable via cache probing (L1/L2)" },
          { item: "Memory access patterns", status: "public", holder: "Attacker", when: "Observable by OS (page-table attacks); mitigated by ORAM" },
          { item: "Enclave secret data", status: "private", holder: "Enclave", when: "Intended private but leaks through side channels" },
          { item: "Power consumption", status: "public", holder: "Attacker", when: "Observable with physical access" },
        ],
        connections:
          "Side-channel risk is why your thesis does not rely on TEEs alone. The hybrid architecture uses ZKPs as the trust anchor (math-based, no side channels) and TEEs as a performance optimization. If the TEE is compromised, the ZKP layer still guarantees correctness.",
        thesisExample:
          "Side channels are the main threat to your TEE layer. During BBS+ verification inside SGX, the pairing computation accesses different memory locations depending on the credential attributes. A cache-timing attack could infer which attributes are present. Your thesis mitigates this with constant-time BBS+ implementation — all attribute slots are processed regardless of disclosure policy, ensuring uniform memory access patterns.",
      },
      {
        name: "Trust Model: TEE vs ZKP",
        analogy:
          "TEE is trusting a bank vault (hardware manufacturer guarantee). ZKP is trusting math itself (no hardware trust needed). Combining both is belt AND suspenders: if the vault is cracked, the math still holds. If the math is too slow, the vault accelerates it.",
        diagram: [
          "┌─────────────┬───────┬────────┐",
          "│             │  TEE  │  ZKP   │",
          "├─────────────┼───────┼────────┤",
          "│ Trust basis │HW mfg │ Math   │",
          "│ Speed       │ Fast  │ Slow   │",
          "│ Side-chan.  │ Risk  │ Immune │",
          "│ Verify cost │ Low   │ Low(*) │",
          "│ Setup trust │ Intel │CRS/SRS │",
          "└─────────────┴───────┴────────┘",
          "(*) on-chain SNARK verification",
          "",
          "Hybrid Architecture:",
          "┌─────┐ fast path ┌─────┐",
          "│ TEE │──────────→│ Sui │",
          "└──┬──┘           └──┬──┘",
          "   │ fallback        │verify",
          "   ▼                 ▼",
          "┌─────┐          ┌───────┐",
          "│ ZKP │─────────→│ proof │",
          "└─────┘ trust    └───────┘",
          "        anchor",
        ].join("\n"),
        keyPoints: [
          "TEE trusts hardware vendor (Intel/AMD): security depends on manufacturing integrity",
          "ZKP trusts mathematical hardness assumptions: no hardware dependency",
          "TEE is fast but vulnerable to side-channel and physical attacks",
          "ZKP is slow (proving takes seconds-minutes) but provides trustless verification",
          "Hybrid approach: TEE for speed, ZKP as fallback trust anchor when TEE is insufficient",
        ],
        publicPrivate: [
          { item: "ZKP assumptions (DLP, pairing hardness)", status: "public", holder: "Everyone", when: "Always (published mathematical assumptions)" },
          { item: "TEE hardware root of trust", status: "private", holder: "CPU manufacturer", when: "Always (embedded in silicon)" },
          { item: "ZKP proof", status: "public", holder: "Everyone", when: "After generation (verifiable by anyone)" },
          { item: "TEE attestation report", status: "public", holder: "Verifier", when: "During attestation (requires trusting manufacturer)" },
          { item: "Computation correctness (hybrid: TEE breaks)", status: "public", holder: "Everyone", when: "ZKP still provides public verification" },
          { item: "Data confidentiality (hybrid: ZKP breaks)", status: "private", holder: "TEE enclave", when: "TEE still provides hardware confidentiality" },
        ],
        connections:
          "This is the central architectural insight of your thesis. On Sui, TEEs accelerate credential issuance and proof generation while ZKP circuits provide the on-chain verification. If a TEE is compromised, users can fall back to pure ZK proofs, maintaining the system security guarantees.",
        thesisExample:
          "Your thesis makes an explicit architectural choice: TEE for speed, ZKP for trust. Low-value payments (coffee, transit) use TEE verification (~1ms, trusting hardware). High-value payments or DeFi interactions use on-chain Groth16 (~500ms, trustless math). If an SGX vulnerability is discovered, the system gracefully degrades to ZKP-only mode — slower but still secure. This dual-path architecture is the core contribution of your thesis.",
      },
    ],
  },
};
