/**
 * Day 3 Study Guide — Blockchain Privacy + Integration
 * Study content with ASCII diagrams, analogies, and thesis connections.
 */

window.DAY3_GUIDE = {
  block1: {
    title: 'Blockchain Privacy (Zcash, Sui, Private Payments)',
    connectionsSummary:
      'Understanding existing privacy approaches reveals WHY a new solution is needed for Sui. Zcash proves ZK works for payments, Monero shows mandatory privacy has UX benefits, but both are standalone chains. Your thesis brings privacy TO an existing programmable chain (Sui) through credentials + ZKP.',
    concepts: [
      {
        name: 'Blockchain Transparency Problem',
        analogy:
          'Publishing your bank statements on a billboard. Every transaction amount, sender, and receiver is visible to the entire world forever. Anyone with a browser can trace your financial life just by looking up your address.',
        diagram: [
          '┌─────────── Transparent Chain ───────────┐',
          '│                                         │',
          '│  Alice ──5 ETH──→ Bob                   │',
          '│  Bob ──2 ETH──→ Carol                   │',
          '│                                         │',
          '│  👁 Everyone sees everything             │',
          '└─────────────────────────────────────────┘',
          '',
          '┌─────────── Privacy Chain ───────────────┐',
          '│                                         │',
          '│  ??? ──??? ──→ ???                       │',
          '│  ??? ──??? ──→ ???                       │',
          '│                                         │',
          '│  Only sender & receiver know details     │',
          '└─────────────────────────────────────────┘',
        ].join('\n'),
        keyPoints: [
          'Pseudonymity is NOT anonymity: addresses are linkable via chain analysis',
          'Companies like Chainalysis de-anonymize users by clustering addresses',
          'Once identity is linked to one address, entire history is exposed',
          'Privacy is a fundamental right, not a tool for illicit activity',
          'Even "private" L2s leak metadata (timing, gas, access patterns)',
        ],
        connections:
          'The transparency problem is the core motivation for the thesis. On Sui, all objects and transactions are public. The thesis builds a privacy layer using anonymous credentials and ZKP so users can transact without revealing identity or amounts.',
      },
      {
        name: 'Zcash & Shielded Transactions',
        analogy:
          'A magical accounting book where entries are encrypted. Auditors can verify the books balance without seeing any individual transaction. Deposits create sealed envelopes (note commitments), and spending reveals nothing except that a valid envelope was consumed.',
        diagram: [
          '┌──────────────────────────────────────┐',
          '│         Zcash Dual-Pool Model         │',
          '│                                       │',
          '│  ┌─────────────┐  ┌───────────────┐  │',
          '│  │ Transparent │  │   Shielded     │  │',
          '│  │    Pool     │  │     Pool       │  │',
          '│  │  (public)   │  │  (encrypted)   │  │',
          '│  └──────┬──────┘  └───────┬────────┘  │',
          '│         │                 │           │',
          '│         │    mint (t→z)   │           │',
          '│         ├────────────────→│           │',
          '│         │                 │           │',
          '│         │   pour (z→t)    │           │',
          '│         │←────────────────┤           │',
          '│         │                 │           │',
          '│         │  zk-SNARK proves validity   │',
          '│         │  without revealing values   │',
          '└──────────────────────────────────────┘',
        ].join('\n'),
        keyPoints: [
          'Sapling protocol uses Jubjub curve for efficient in-circuit arithmetic',
          'Note commitment tree (Merkle tree) stores encrypted transaction outputs',
          'Nullifiers prevent double-spending without revealing which note was spent',
          'Groth16 proofs: ~200 bytes, verify in ~10ms, but trusted setup required',
          'Optional transparency: users choose per-transaction (most stay transparent)',
        ],
        connections:
          'Zcash proves that ZK-based private payments work at scale. The thesis adopts a similar commitment/nullifier model for private payments on Sui, but adds credential-gated access so that privacy does not preclude compliance.',
      },
      {
        name: 'Monero Privacy',
        analogy:
          'Sending a letter through 10 identical mailboxes simultaneously. Observers see all 10 but cannot tell which one contains your real letter. Every transaction automatically includes decoys, so privacy is the default, not an opt-in feature.',
        diagram: [
          '┌─────────── Ring Signature ────────────┐',
          '│                                       │',
          '│  Real input ─→ ┐                      │',
          '│  Decoy #1  ─→ ├─→ Ring ─→ Output      │',
          '│  Decoy #2  ─→ ├─  Sig     (stealth    │',
          '│  Decoy #3  ─→ ┘          address)     │',
          '│                                       │',
          '│  Which input is real? Nobody knows.    │',
          '│                                       │',
          '│  ┌─────────────────────────────────┐  │',
          '│  │ Stealth addr: one-time key       │  │',
          '│  │ RingCT: amount encrypted         │  │',
          '│  │ Bulletproofs: range proof         │  │',
          '│  └─────────────────────────────────┘  │',
          '└───────────────────────────────────────┘',
        ].join('\n'),
        keyPoints: [
          'Mandatory privacy: every transaction uses ring signatures (no opt-in choice)',
          'Ring signatures mix real input with decoy inputs (currently ring size 16)',
          'Stealth addresses: receiver gets a one-time address per transaction',
          'RingCT hides transaction amounts using Pedersen commitments',
          'Bulletproofs provide efficient range proofs without trusted setup',
        ],
        connections:
          'Monero shows that mandatory privacy improves anonymity sets dramatically compared to opt-in (Zcash). The thesis considers mandatory privacy for its payment layer but needs compliance hooks that Monero deliberately avoids.',
      },
      {
        name: 'Tornado Cash & Mixer Model',
        analogy:
          'A coin laundry: you put your traceable coins in, wait, and withdraw unlinkable coins. The anonymity set is everyone who used the laundry at the same time. The bigger the crowd, the better your privacy.',
        diagram: [
          '┌────────── Tornado Cash Flow ──────────┐',
          '│                                       │',
          '│  Deposit (fixed amount, e.g. 1 ETH):  │',
          '│  User ─→ commitment ─→ Merkle Tree    │',
          '│                          │             │',
          '│  ┌───┬───┬───┬───┬───┐  │             │',
          '│  │ c1│ c2│ c3│ c4│ c5│  │ leaves      │',
          '│  └───┴───┴───┴───┴───┘  │             │',
          '│         Merkle root ←───┘             │',
          '│                                       │',
          '│  Withdraw (new address):              │',
          '│  ZK proof: "I know a secret s where   │',
          '│  hash(s) is in the Merkle tree"       │',
          '│  + nullifier (prevents double-spend)  │',
          '│                                       │',
          '│  No link between deposit & withdrawal │',
          '└───────────────────────────────────────┘',
        ].join('\n'),
        keyPoints: [
          'Merkle tree of commitments: each deposit adds a leaf hash(secret, nullifier)',
          'Withdrawal proves membership via ZK proof without revealing which leaf',
          'Nullifier hash published on withdrawal to prevent double-spending',
          'Fixed denominations (0.1, 1, 10, 100 ETH) maximize anonymity set overlap',
          'OFAC sanctions (2022) raised critical questions about protocol-level privacy vs. compliance',
        ],
        connections:
          'Tornado Cash demonstrates the commitment/nullifier pattern the thesis reuses. However, its regulatory troubles highlight why the thesis includes compliance mechanisms (viewing keys, credential-gated access) that Tornado Cash lacked.',
      },
      {
        name: 'Sui Architecture & Privacy Gaps',
        analogy:
          'Sui is like a post office with numbered lockers (objects) instead of named mailboxes (accounts). Each locker is independent, so you can open multiple lockers simultaneously (parallel execution). But everything inside is still visible to anyone walking by.',
        diagram: [
          '┌──────────── Sui Object Model ─────────┐',
          '│                                       │',
          '│  ┌─────────┐ ┌─────────┐ ┌─────────┐ │',
          '│  │ Owned   │ │ Owned   │ │ Shared  │ │',
          '│  │ Object  │ │ Object  │ │ Object  │ │',
          '│  │ (Alice) │ │ (Bob)   │ │ (DEX)   │ │',
          '│  └────┬────┘ └────┬────┘ └────┬────┘ │',
          '│       │           │           │      │',
          '│  No contention: parallel execution    │',
          '│                                       │',
          '│  ┌─────────────────────────────────┐  │',
          '│  │  Move Modules (smart contracts)  │  │',
          '│  │  define object types & rules     │  │',
          '│  └─────────────────────────────────┘  │',
          '│                                       │',
          '│  Privacy gaps:                        │',
          '│  - All objects publicly readable       │',
          '│  - All transactions publicly visible   │',
          '│  - No native encryption or hiding      │',
          '│  - Object ownership is transparent     │',
          '└───────────────────────────────────────┘',
        ].join('\n'),
        keyPoints: [
          'Object-centric model: state is objects, not global accounts',
          'Parallel execution on owned objects (no locks needed)',
          'Move language enforces resource safety (no duplication, no loss)',
          'No native privacy layer: all objects and transactions are public',
          'Opportunity: build a privacy-preserving layer on top using ZKP + TEE',
        ],
        connections:
          'Sui is the target chain for the thesis. Its object model is ideal for representing credentials as objects, and its parallel execution means privacy operations on owned objects do not bottleneck the chain. The gap is privacy, which the thesis fills.',
      },
      {
        name: 'Private Payment Requirements',
        analogy:
          'The privacy trilemma: like building a house that is cheap, fast, AND beautiful, you cannot have full privacy, full compliance, AND full scalability at once. Every system makes tradeoffs. The thesis seeks the sweet spot where enough privacy, enough compliance, and enough performance coexist.',
        diagram: [
          '          Privacy',
          '            /\\',
          '           /  \\',
          '          /    \\',
          '         / Zcash \\',
          '        / Monero  \\',
          '       /────────────\\',
          '      /   THESIS     \\',
          '     /    TARGET      \\',
          '    /──────────────────\\',
          '   /                    \\',
          '  Compliance ──────── Scalability',
          '',
          '  Monero:   max privacy, no compliance',
          '  Zcash:    opt-in privacy, some compliance',
          '  Tornado:  mixer privacy, zero compliance',
          '  Thesis:   ZKP privacy + credential compliance',
        ].join('\n'),
        keyPoints: [
          'Sender privacy: hide who is paying',
          'Receiver privacy: hide who is being paid',
          'Amount hiding: conceal transaction values via Pedersen commitments',
          'Compliance hooks: viewing keys let authorized auditors decrypt selectively',
          'Low-value threshold: lighter ZK verification for small payments, heavier proofs for large ones',
        ],
        connections:
          'This concept frames the exact design space of the thesis. The goal is to achieve sender/receiver/amount privacy on Sui while retaining compliance via anonymous credentials (KYC without identity disclosure) and viewing keys for auditors.',
      },
    ],
  },
  block2: {
    title: 'ZKP+TEE Integration + Thesis Architecture',
    connectionsSummary:
      'This is YOUR thesis architecture coming together. Every concept from Days 1-3 converges here: elliptic curves, BBS+ signatures, anonymous credentials, selective disclosure, ZK proofs, TEE acceleration, private payments on Sui. The last concept map IS your thesis outline.',
    concepts: [
      {
        name: 'Why Combine ZKP + TEE',
        analogy:
          'Belt AND suspenders. ZKP is the belt: a mathematical guarantee that cannot break regardless of computational power. TEE is the suspenders: a hardware guarantee that is fast but could theoretically fail if the chip is compromised. Together, even if one fails, your security holds.',
        diagram: [
          '┌───────────────────────────────────────┐',
          '│          Trust / Speed Tradeoff        │',
          '│                                       │',
          '│  Pure ZKP Path:                       │',
          '│  ┌──────┐   slow    ┌──────────────┐ │',
          '│  │Input │──proving──→│ Trustless    │ │',
          '│  └──────┘  (mins)   │ Verification │ │',
          '│                     └──────────────┘ │',
          '│                                       │',
          '│  Pure TEE Path:                       │',
          '│  ┌──────┐   fast    ┌──────────────┐ │',
          '│  │Input │──compute──→│ Trust HW     │ │',
          '│  └──────┘  (ms)     │ Attestation  │ │',
          '│                     └──────────────┘ │',
          '│                                       │',
          '│  Hybrid Path (thesis):                │',
          '│  ┌──────┐  fast  ┌─────┐  ┌────────┐│',
          '│  │Input │──────→│ TEE │──→│ZK Proof ││',
          '│  └──────┘       │witness│ │verifier ││',
          '│                 └─────┘  └────────┘ │',
          '│  Speed of TEE + trustlessness of ZKP │',
          '└───────────────────────────────────────┘',
        ].join('\n'),
        keyPoints: [
          'ZKP = trustless but slow: Groth16 proving can take seconds to minutes',
          'TEE = fast but trust-dependent: computation in ms, but assumes hardware integrity',
          'Hybrid reduces trust assumptions while maintaining performance',
          'If TEE is compromised, ZKP verification still catches invalid proofs',
          'Fallback to pure ZKP if TEE attestation fails (graceful degradation)',
        ],
        connections:
          'The thesis uses this hybrid model as its core architecture. TEE handles the expensive witness generation (credential decryption, balance checks) while ZKP provides the on-chain verification that requires no trust in hardware.',
      },
      {
        name: 'Hybrid Architecture Patterns',
        analogy:
          'A courtroom with a secure deliberation room. The jury (TEE) deliberates privately and quickly, then presents a verdict (proof). The judge (ZKP verifier) can independently verify the verdict is correct without seeing the private deliberation.',
        diagram: [
          '┌──── TEE-Assisted Proving Pipeline ────┐',
          '│                                       │',
          '│  Private Input                        │',
          '│       │                               │',
          '│       ▼                               │',
          '│  ┌─────────────────────┐              │',
          '│  │    TEE Enclave      │              │',
          '│  │  ┌───────────────┐  │              │',
          '│  │  │ Decrypt cred  │  │              │',
          '│  │  │ Check balance │  │  Attestation │',
          '│  │  │ Build witness │  │──────┐       │',
          '│  │  └───────────────┘  │      │       │',
          '│  └─────────┬───────────┘      │       │',
          '│            │ witness           │       │',
          '│            ▼                   ▼       │',
          '│  ┌──────────────┐    ┌──────────────┐ │',
          '│  │  ZK Prover   │    │  Attestation │ │',
          '│  │  (Groth16)   │    │   Verifier   │ │',
          '│  └──────┬───────┘    └──────────────┘ │',
          '│         │ proof                       │',
          '│         ▼                              │',
          '│  ┌──────────────────┐                 │',
          '│  │  On-Chain Verify │  10-100x faster │',
          '│  │   (Sui Move)    │  than pure ZKP  │',
          '│  └──────────────────┘                 │',
          '└───────────────────────────────────────┘',
        ].join('\n'),
        keyPoints: [
          'TEE performs witness generation: decrypt credentials, verify balances, compute intermediate values',
          'ZKP proves the computation was correct without revealing private inputs',
          'Attestation provides evidence the TEE ran genuine code on genuine hardware',
          'Latency reduction of 10-100x compared to pure ZKP proving',
          'If TEE is compromised, system degrades to pure ZKP (slower but still secure)',
        ],
        connections:
          'This pipeline is the thesis proving architecture. User private data enters the TEE, gets processed into a witness, and the ZK proof is generated and verified on Sui. The TEE never exposes private data; the ZKP ensures correctness publicly.',
      },
      {
        name: 'Anonymous Credentials on Sui',
        analogy:
          'A digital ID card system built on Sui objects. Each credential is a Sui object, issuance is a transaction, and verification uses ZKP so the credential object itself never reveals its contents. Like showing a bouncer a hologram that proves you are over 21 without showing your birthdate or name.',
        diagram: [
          '┌─── Credential Lifecycle on Sui ───────┐',
          '│                                       │',
          '│  1. ISSUANCE                          │',
          '│  ┌────────┐  BBS+   ┌──────────────┐ │',
          '│  │ Issuer │──sign──→│ Credential   │ │',
          '│  │ (KYC)  │        │ (Sui Object) │ │',
          '│  └────────┘        └──────┬───────┘ │',
          '│                           │          │',
          '│  2. STORAGE               ▼          │',
          '│              ┌──────────────────┐    │',
          '│              │   User Wallet    │    │',
          '│              │  (owns object)   │    │',
          '│              └────────┬─────────┘    │',
          '│                      │               │',
          '│  3. PRESENTATION      ▼               │',
          '│  ┌──────────────────────────────────┐ │',
          '│  │ ZK Proof: "I have a valid cred   │ │',
          '│  │ with attribute age >= 18"         │ │',
          '│  │ (reveals NOTHING else)            │ │',
          '│  └───────────────┬──────────────────┘ │',
          '│                  │                    │',
          '│  4. VERIFICATION  ▼                    │',
          '│  ┌──────────────────────────────────┐ │',
          '│  │ Sui Move Contract verifies proof │ │',
          '│  │ on-chain (Groth16 verifier)      │ │',
          '│  └──────────────────────────────────┘ │',
          '└───────────────────────────────────────┘',
        ].join('\n'),
        keyPoints: [
          'Credential as Sui object: leverages Move resource safety (cannot duplicate or destroy)',
          'BBS+ signatures enable selective disclosure of individual attributes',
          'On-chain verification via Groth16: ~200 byte proof, cheap to verify in Move',
          'Privacy-preserving presentation: prove properties without revealing credential contents',
          'Issuer cannot track where or when credentials are used (unlinkability)',
        ],
        connections:
          'This is the credential layer of the thesis. BBS+ issuance creates Sui objects that users own. Selective disclosure via ZKP allows proving KYC compliance without revealing identity, which gates access to the private payment layer.',
      },
      {
        name: 'Private Payment Flow',
        analogy:
          'A vending machine with a privacy screen. You prove you have enough money (ZKP), insert the right amount (encrypted), and the machine gives you the item. Nobody in line sees how much you paid or your balance. But a compliance officer with a special key could audit the transaction if required.',
        diagram: [
          '┌──── End-to-End Private Payment ───────┐',
          '│                                       │',
          '│  Sender                               │',
          '│  ┌──────────────────────────────┐     │',
          '│  │ 1. Prove valid credential    │     │',
          '│  │    (ZKP: "I passed KYC")     │     │',
          '│  │ 2. Create amount commitment  │     │',
          '│  │    C = g^amount * h^blinding  │     │',
          '│  │ 3. ZK proof of solvency      │     │',
          '│  │    (balance >= amount)        │     │',
          '│  │ 4. Generate nullifier         │     │',
          '│  └──────────────┬───────────────┘     │',
          '│                 │                     │',
          '│                 ▼                      │',
          '│  ┌──────────────────────────────┐     │',
          '│  │    Sui Chain (Move Contract)  │     │',
          '│  │  - Verify credential proof    │     │',
          '│  │  - Verify solvency proof      │     │',
          '│  │  - Check nullifier unused     │     │',
          '│  │  - Record new commitment      │     │',
          '│  └──────────────┬───────────────┘     │',
          '│                 │                     │',
          '│                 ▼                      │',
          '│  Receiver                             │',
          '│  ┌──────────────────────────────┐     │',
          '│  │ 5. Decrypt with viewing key  │     │',
          '│  │ 6. Claim funds               │     │',
          '│  └──────────────────────────────┘     │',
          '└───────────────────────────────────────┘',
        ].join('\n'),
        keyPoints: [
          'Credential-gated access: must prove valid KYC credential via ZKP before transacting',
          'Amount hiding via Pedersen commitments: C = g^v * h^r (additively homomorphic)',
          'Nullifiers prevent double-spending without revealing which commitment was consumed',
          'Viewing keys allow authorized auditors to decrypt specific transactions',
          'Low-value threshold: transactions below a limit use lighter proofs for speed',
        ],
        connections:
          'This is the payment layer of the thesis. It combines the credential check (Block 2, concept 3) with the commitment/nullifier model (from Zcash/Tornado Cash in Block 1) and adds compliance via viewing keys. This flow runs on Sui with TEE-accelerated proving.',
      },
      {
        name: 'Post-Quantum Considerations',
        analogy:
          'Preparing for a flood before it rains. Quantum computers do not exist at scale yet, but harvest-now-decrypt-later attacks mean data encrypted today could be broken tomorrow. Credentials issued now must still be unforgeable in 10 years.',
        diagram: [
          '┌────── Migration Timeline ─────────────┐',
          '│                                       │',
          '│  NOW                 TRANSITION   PQ  │',
          '│   │                    │           │  │',
          '│   ▼                    ▼           ▼  │',
          '│  ┌────────┐  ┌────────────┐  ┌─────┐ │',
          '│  │BBS+    │  │ Hybrid     │  │Lat- │ │',
          '│  │Groth16 │→ │ BBS+ +     │→ │tice │ │',
          '│  │ECDSA   │  │ lattice    │  │based│ │',
          '│  └────────┘  └────────────┘  └─────┘ │',
          '│                                       │',
          '│  What changes:                        │',
          '│  ├─ Signatures: BBS+ → lattice BBS    │',
          '│  ├─ ZK proofs: Groth16 → STARK/hash   │',
          '│  └─ Key sizes: ~256b → ~1KB+          │',
          '│                                       │',
          '│  What stays:                          │',
          '│  ├─ Commitment/nullifier model         │',
          '│  ├─ TEE acceleration pattern           │',
          '│  └─ Sui object model & Move contracts  │',
          '└───────────────────────────────────────┘',
        ].join('\n'),
        keyPoints: [
          'Harvest-now-decrypt-later: adversaries store encrypted data to break later with quantum computers',
          'Lattice-based alternatives (e.g., Lether) offer post-quantum credential signatures',
          'Hash-based signatures (SPHINCS+) provide quantum-safe but larger proofs',
          'NIST PQC standardization (ML-KEM, ML-DSA) provides migration targets',
          'Thesis architecture is designed for modular crypto swap: change primitives, keep structure',
        ],
        connections:
          'The thesis addresses post-quantum readiness by designing a modular architecture where cryptographic primitives (BBS+, Groth16) can be swapped for lattice-based alternatives without changing the overall system design. The Lether paper (Day 3 reading) provides a concrete post-quantum payment scheme.',
      },
      {
        name: 'Full Thesis Architecture',
        analogy:
          'Building a privacy-preserving city on Sui. Credentials are your ID cards (BBS+), payments go through private channels (ZKP), and TEEs are the fast-track security checkpoints. The city has rules (compliance) but respects your right to walk the streets without being tracked.',
        diagram: [
          '┌─────────────────────────────────────────────────────────┐',
          '│              THESIS ARCHITECTURE OVERVIEW               │',
          '│     Anonymous Credentials + ZKP + TEE on Sui           │',
          '├─────────────────────────────────────────────────────────┤',
          '│                                                         │',
          '│  ┌───────────────────────────────────────────────────┐  │',
          '│  │                   USER WALLET                     │  │',
          '│  │  ┌─────────────┐  ┌───────────┐  ┌────────────┐  │  │',
          '│  │  │ BBS+ Cred   │  │ Private   │  │ Viewing    │  │  │',
          '│  │  │ (Sui Obj)   │  │ Balance   │  │ Keys       │  │  │',
          '│  │  └──────┬──────┘  └─────┬─────┘  └─────┬──────┘  │  │',
          '│  └─────────┼───────────────┼───────────────┼─────────┘  │',
          '│            │               │               │            │',
          '│            ▼               ▼               │            │',
          '│  ┌───────────────────────────────────┐    │            │',
          '│  │         TEE ENCLAVE                │    │            │',
          '│  │  ┌───────────┐  ┌───────────────┐ │    │            │',
          '│  │  │ Decrypt   │  │ Compute       │ │    │            │',
          '│  │  │ Credential│  │ Witness        │ │    │            │',
          '│  │  └─────┬─────┘  └───────┬───────┘ │    │            │',
          '│  │        └────────┬───────┘         │    │            │',
          '│  │                 │ witness          │    │            │',
          '│  └─────────────────┼─────────────────┘    │            │',
          '│                    ▼                       │            │',
          '│  ┌───────────────────────────────────┐    │            │',
          '│  │         ZK PROVER (Groth16)        │    │            │',
          '│  │  ┌─────────────┐ ┌──────────────┐ │    │            │',
          '│  │  │ Credential  │ │ Payment      │ │    │            │',
          '│  │  │ Proof       │ │ Proof        │ │    │            │',
          '│  │  │ (valid KYC) │ │ (solvency)   │ │    │            │',
          '│  │  └──────┬──────┘ └──────┬───────┘ │    │            │',
          '│  └─────────┼───────────────┼─────────┘    │            │',
          '│            │               │              │            │',
          '│            ▼               ▼              ▼            │',
          '│  ┌─────────────────────────────────────────────────┐   │',
          '│  │              SUI BLOCKCHAIN (L1)                │   │',
          '│  │                                                 │   │',
          '│  │  ┌──────────────┐  ┌─────────────────────────┐ │   │',
          '│  │  │  Credential  │  │   Payment Contract      │ │   │',
          '│  │  │  Verifier    │  │  ┌───────────────────┐  │ │   │',
          '│  │  │  (Move)      │  │  │ Commitment Tree   │  │ │   │',
          '│  │  │              │  │  │ Nullifier Set     │  │ │   │',
          '│  │  │  - Verify    │  │  │ Verify ZK Proofs  │  │ │   │',
          '│  │  │    BBS+ ZKP  │  │  └───────────────────┘  │ │   │',
          '│  │  └──────────────┘  └─────────────────────────┘ │   │',
          '│  │                                                 │   │',
          '│  │  ┌─────────────────────────────────────────┐   │   │',
          '│  │  │         Compliance Layer                 │   │   │',
          '│  │  │  - Viewing keys → auditor access         │   │   │',
          '│  │  │  - Credential revocation list            │   │   │',
          '│  │  │  - Low-value threshold logic             │   │   │',
          '│  │  └─────────────────────────────────────────┘   │   │',
          '│  └─────────────────────────────────────────────────┘   │',
          '│                                                         │',
          '│  Legend:                                                │',
          '│  Credential Layer: BBS+ issuance + selective disclosure │',
          '│  Payment Layer:    commitments + nullifiers + proofs    │',
          '│  TEE Layer:        witness generation + attestation     │',
          '│  Compliance Layer: viewing keys + audit + revocation    │',
          '└─────────────────────────────────────────────────────────┘',
        ].join('\n'),
        keyPoints: [
          'Layered architecture: Sui L1 base + credential layer + payment layer + TEE acceleration + compliance',
          'Credential layer: BBS+ issuance by trusted authorities, selective disclosure via ZKP, stored as Sui objects',
          'Payment layer: Pedersen commitments hide amounts, nullifiers prevent double-spend, ZK proofs ensure validity',
          'TEE acceleration layer: enclave computes witnesses for fast proof generation, attestation verifies enclave integrity',
          'Compliance layer: viewing keys for authorized auditors, credential revocation for banned users, low-value threshold for lighter verification',
        ],
        connections:
          'This diagram IS the thesis. Every concept from all three study days feeds into one component: elliptic curves power BBS+ and Pedersen commitments, ZKP systems (Groth16) verify credentials and payments, TEEs accelerate proving, and Sui provides the programmable base layer. The thesis contribution is integrating these into a coherent privacy-preserving payment system with compliance.',
      },
    ],
  },
};
