/**
 * Flashcard Data — Thesis Study Plan
 * Mobile spaced-repetition deck for bus commutes.
 * ~80 cards covering all 6 thesis chapters + Rust.
 * No complex math — conceptual knowledge, definitions, key facts, acronyms.
 */

window.FLASHCARDS = [

  /* ===================== CH 2.1 — Anonymous Credentials ===================== */

  {
    id: 'ac-01',
    chapter: 'ch21',
    category: 'definition',
    front: 'What is a BBS+ signature?',
    back: 'A pairing-based, rerandomizable signature scheme enabling selective disclosure and zero-knowledge proofs of possession. Core primitive for anonymous credentials.',
    tags: ['bbs', 'signature', 'selective-disclosure'],
  },
  {
    id: 'ac-02',
    chapter: 'ch21',
    category: 'definition',
    front: 'What does "selective disclosure" mean in credential systems?',
    back: 'A holder reveals only a chosen subset of signed attributes (e.g., "age > 18") to a verifier, without exposing the rest or the full credential.',
    tags: ['selective-disclosure', 'credentials'],
  },
  {
    id: 'ac-03',
    chapter: 'ch21',
    category: 'acronym',
    front: 'What does "CL signature" stand for?',
    back: 'Camenisch-Lysyanskaya signature — a pairing-based scheme allowing proofs of knowledge of a signature without revealing it. Predecessor to BBS+.',
    tags: ['cl', 'camenisch', 'lysyanskaya'],
  },
  {
    id: 'ac-04',
    chapter: 'ch21',
    category: 'acronym',
    front: 'What does "PS signature" stand for?',
    back: 'Pointcheval-Sanders signature — compact randomizable signature scheme in bilinear groups, used in ACL (Anonymous Credential Light).',
    tags: ['ps', 'pointcheval', 'sanders'],
  },
  {
    id: 'ac-05',
    chapter: 'ch21',
    category: 'fact',
    front: 'What security model does BBS+ use?',
    back: 'EUF-CMA (Existential Unforgeability under Chosen-Message Attack) under q-SDH assumption in bilinear groups (ROM + AGM).',
    tags: ['bbs', 'security', 'euf-cma'],
  },
  {
    id: 'ac-06',
    chapter: 'ch21',
    category: 'definition',
    front: 'What is "issuer hiding" in anonymous credentials?',
    back: 'A property where the verifier cannot determine which issuer signed the credential, hiding the credential chain from the verifier.',
    tags: ['issuer-hiding', 'privacy'],
  },
  {
    id: 'ac-07',
    chapter: 'ch21',
    category: 'definition',
    front: 'What is threshold issuance in credential systems?',
    back: 'Multiple issuers jointly sign a credential using a t-of-n threshold scheme — no single issuer can issue alone, reducing trust concentration.',
    tags: ['threshold', 'issuance', 'multi-party'],
  },
  {
    id: 'ac-08',
    chapter: 'ch21',
    category: 'acronym',
    front: 'What does "DID" stand for?',
    back: 'Decentralized Identifier — a W3C standard for self-sovereign, globally unique identifiers not relying on a central registry.',
    tags: ['did', 'w3c', 'ssi'],
  },
  {
    id: 'ac-09',
    chapter: 'ch21',
    category: 'acronym',
    front: 'What does "SSI" stand for?',
    back: 'Self-Sovereign Identity — a model where users control their identity data directly, without relying on centralized identity providers.',
    tags: ['ssi', 'identity'],
  },
  {
    id: 'ac-10',
    chapter: 'ch21',
    category: 'fact',
    front: 'What is the W3C standard for anonymous credentials?',
    back: 'Verifiable Credentials (VC) Data Model — defines a JSON-LD format for credentials signed with various schemes including BBS+ Data Integrity.',
    tags: ['w3c', 'vc', 'json-ld'],
  },
  {
    id: 'ac-11',
    chapter: 'ch21',
    category: 'definition',
    front: 'What is credential revocation in the context of anonymous credentials?',
    back: 'A mechanism to invalidate issued credentials without breaking holder anonymity. Approaches include accumulators (RSA, Merkle), epoch-based, and CRLs.',
    tags: ['revocation', 'accumulator'],
  },
  {
    id: 'ac-12',
    chapter: 'ch21',
    category: 'fact',
    front: 'What is the "SoK: Anonymous Credentials for Digital Identity Wallets"?',
    back: 'A 2026 systematization-of-knowledge paper (ePrint 2026/330) surveying anonymous credential schemes for EU digital wallets and eIDAS 2.0.',
    tags: ['sok', 'eidas', 'survey'],
  },
  {
    id: 'ac-13',
    chapter: 'ch21',
    category: 'definition',
    front: 'What is a "proof of possession" in credential systems?',
    back: 'A ZK proof that the holder possesses a valid credential (knows the signature) without revealing the signature itself — prevents credential sharing.',
    tags: ['proof-of-possession', 'zkp'],
  },
  {
    id: 'ac-14',
    chapter: 'ch21',
    category: 'fact',
    front: 'What is eIDAS 2.0?',
    back: 'EU regulation for digital identity wallets (EUDIW). Mandates selective disclosure and pseudonymity. Target: 80% EU citizens by 2026.',
    tags: ['eidas', 'eu', 'regulation'],
  },
  {
    id: 'ac-15',
    chapter: 'ch21',
    category: 'definition',
    front: 'What is "rerandomization" of a signature?',
    back: 'Producing a new, unlinkable signature on the same message from an existing one — core to BBS+ and PS, preventing verifier-to-issuer correlation.',
    tags: ['rerandomization', 'unlinkability', 'bbs'],
  },

  /* ===================== CH 2.2 — Confidential Transactions ===================== */

  {
    id: 'ct-01',
    chapter: 'ch22',
    category: 'definition',
    front: 'What is a Pedersen commitment?',
    back: 'A perfectly hiding, computationally binding commitment: C = r·G + v·H. Used to commit to a value v with blinding factor r without revealing v.',
    tags: ['pedersen', 'commitment', 'hiding'],
  },
  {
    id: 'ct-02',
    chapter: 'ch22',
    category: 'definition',
    front: 'What are Bulletproofs?',
    back: 'Short, non-interactive range proofs (no trusted setup) using inner-product arguments. Prove a committed value is in [0, 2^n] in O(log n) proof size.',
    tags: ['bulletproofs', 'range-proof', 'no-trusted-setup'],
  },
  {
    id: 'ct-03',
    chapter: 'ch22',
    category: 'acronym',
    front: 'What does "UTT" stand for?',
    back: 'UnTraceable Transactions — Tomescu et al. 2022 (IACR 2022/452). A confidential payment scheme underlying utt-rs, built on Pedersen + BBS+ + range proofs.',
    tags: ['utt', 'tomescu', 'confidential-payments'],
  },
  {
    id: 'ct-04',
    chapter: 'ch22',
    category: 'definition',
    front: 'What is a range proof?',
    back: 'A zero-knowledge proof that a committed value lies within a given range (e.g., [0, 2^64]) without revealing the actual value. Prevents negative balances.',
    tags: ['range-proof', 'zkp'],
  },
  {
    id: 'ct-05',
    chapter: 'ch22',
    category: 'fact',
    front: 'What does "homomorphic" mean for Pedersen commitments?',
    back: 'Commit(a) + Commit(b) = Commit(a+b). Enables verifying that outputs sum correctly without revealing individual amounts — key for confidential transactions.',
    tags: ['homomorphic', 'pedersen'],
  },
  {
    id: 'ct-06',
    chapter: 'ch22',
    category: 'acronym',
    front: 'What does "RingCT" stand for?',
    back: 'Ring Confidential Transactions — Monero\'s scheme combining ring signatures (sender anonymity) with Pedersen commitments (amount hiding).',
    tags: ['ringct', 'monero', 'ring-signatures'],
  },
  {
    id: 'ct-07',
    chapter: 'ch22',
    category: 'definition',
    front: 'What are "Veiled Coins" on Sui?',
    back: 'Mysten Labs\' confidential asset scheme on Sui using twisted ElGamal encryption + Sigma proofs for balance confidentiality within the Move VM.',
    tags: ['veiled', 'sui', 'elgamal'],
  },
  {
    id: 'ct-08',
    chapter: 'ch22',
    category: 'fact',
    front: 'What is the key advantage of Bulletproofs++ over Bulletproofs?',
    back: 'Smaller proof size and faster verification by using improved inner-product arguments. Advisor recommends Bulletproofs++ for the thesis implementation.',
    tags: ['bulletproofs++', 'optimization'],
  },
  {
    id: 'ct-09',
    chapter: 'ch22',
    category: 'definition',
    front: 'What is "balance binding" in confidential transactions?',
    back: 'Property ensuring sum(inputs) = sum(outputs) + fee, verified by checking that commitment differences cancel to zero — prevents money creation.',
    tags: ['balance-binding', 'soundness'],
  },
  {
    id: 'ct-10',
    chapter: 'ch22',
    category: 'definition',
    front: 'What is twisted ElGamal encryption?',
    back: 'ElGamal variant where ciphertext is (r·G, r·PK + v·H). Allows homomorphic addition and decryption by the key holder. Used in Veiled Coins and UTT.',
    tags: ['elgamal', 'twisted', 'encryption'],
  },
  {
    id: 'ct-11',
    chapter: 'ch22',
    category: 'fact',
    front: 'What is "Confidential Assets" in the context of Elements/Liquid?',
    back: 'Blockstream\'s protocol (2017, Poelstra et al.) extending Bitcoin with Pedersen commitments and range proofs to hide transaction amounts on sidechains.',
    tags: ['confidential-assets', 'blockstream', 'liquid'],
  },
  {
    id: 'ct-12',
    chapter: 'ch22',
    category: 'definition',
    front: 'What is a Sigma protocol?',
    back: 'A 3-move interactive proof (commit, challenge, respond) convertible to non-interactive via Fiat-Shamir. Used for equality, knowledge, and range proofs.',
    tags: ['sigma', 'fiat-shamir', 'interactive-proof'],
  },

  /* ===================== CH 2.3 — TEE ===================== */

  {
    id: 'tee-01',
    chapter: 'ch23',
    category: 'acronym',
    front: 'What does "TEE" stand for?',
    back: 'Trusted Execution Environment — an isolated CPU environment (e.g., Intel SGX, ARM TrustZone) that runs code and handles data confidentially from the OS.',
    tags: ['tee', 'definition'],
  },
  {
    id: 'tee-02',
    chapter: 'ch23',
    category: 'acronym',
    front: 'What does "SGX" stand for?',
    back: 'Software Guard Extensions — Intel\'s TEE providing encrypted enclaves in user space, isolated from OS, hypervisor, and other processes.',
    tags: ['sgx', 'intel', 'enclave'],
  },
  {
    id: 'tee-03',
    chapter: 'ch23',
    category: 'fact',
    front: 'Which side-channel attack breaks Intel SGX via AVX gather instructions?',
    back: 'Downfall (CVE-2022-40982) — leaks SGX secrets via speculative GATHER execution. Forces Intel to disable SGX on affected CPUs without microcode.',
    tags: ['downfall', 'cve', 'side-channel', 'sgx'],
  },
  {
    id: 'tee-04',
    chapter: 'ch23',
    category: 'definition',
    front: 'What is remote attestation in TEE?',
    back: 'A cryptographic protocol where an enclave proves to a remote party that it runs specific code on a genuine TEE, signed by the hardware manufacturer.',
    tags: ['attestation', 'remote', 'tee'],
  },
  {
    id: 'tee-05',
    chapter: 'ch23',
    category: 'acronym',
    front: 'What does "TDX" stand for?',
    back: 'Trust Domain Extensions — Intel\'s next-gen TEE for full VM isolation (vs. SGX process-level). The successor approach for cloud confidential computing.',
    tags: ['tdx', 'intel', 'vm'],
  },
  {
    id: 'tee-06',
    chapter: 'ch23',
    category: 'definition',
    front: 'What is AWS Nitro Enclaves?',
    back: 'Amazon\'s TEE product based on isolated VMs with no persistent storage, no external networking, and attestation via Nitro hypervisor. Used for key management.',
    tags: ['nitro', 'aws', 'cloud-tee'],
  },
  {
    id: 'tee-07',
    chapter: 'ch23',
    category: 'acronym',
    front: 'What does "DICE" stand for in TEE context?',
    back: 'Device Identifier Composition Engine — a FIDO/TCG standard for hardware-rooted identity and attestation chaining from boot to application layer.',
    tags: ['dice', 'fido', 'attestation'],
  },
  {
    id: 'tee-08',
    chapter: 'ch23',
    category: 'acronym',
    front: 'What does "RATS" stand for in IETF?',
    back: 'Remote Attestation Procedures — IETF framework (RFC 9334) defining attester/verifier/relying-party roles for standardized TEE attestation.',
    tags: ['rats', 'ietf', 'rfc'],
  },
  {
    id: 'tee-09',
    chapter: 'ch23',
    category: 'fact',
    front: 'What is the "Spectre" attack and why does it matter for TEEs?',
    back: 'Spectre (CVE-2017-5753) exploits speculative execution to read across process boundaries — bypasses SGX isolation and leaks enclave memory via side channels.',
    tags: ['spectre', 'speculative-execution', 'sgx'],
  },
  {
    id: 'tee-10',
    chapter: 'ch23',
    category: 'definition',
    front: 'What is "sealing" in Intel SGX?',
    back: 'Encrypting enclave data to disk using a CPU-derived key tied to the enclave identity. Only the same enclave on the same CPU can unseal the data.',
    tags: ['sealing', 'sgx', 'persistence'],
  },
  {
    id: 'tee-11',
    chapter: 'ch23',
    category: 'definition',
    front: 'What is a "Trusted Computing Base" (TCB)?',
    back: 'The minimal set of hardware and software that must be trusted for a security guarantee to hold. Smaller TCB = smaller attack surface.',
    tags: ['tcb', 'trusted-computing'],
  },
  {
    id: 'tee-12',
    chapter: 'ch23',
    category: 'fact',
    front: 'What does "Gramine" provide for SGX?',
    back: 'A library OS (libOS) that runs unmodified Linux applications inside SGX enclaves — dramatically reduces porting effort for existing codebases.',
    tags: ['gramine', 'sgx', 'libos'],
  },

  /* ===================== CH 2.4 — Private Payments ===================== */

  {
    id: 'pp-01',
    chapter: 'ch24',
    category: 'fact',
    front: 'What privacy technology does Zcash use?',
    back: 'zk-SNARKs (Groth16) over BLS12-381 for shielded transactions. Sapling (2018) made proofs fast enough for mobile; Orchard (2022) uses Halo2.',
    tags: ['zcash', 'groth16', 'sapling'],
  },
  {
    id: 'pp-02',
    chapter: 'ch24',
    category: 'fact',
    front: 'What privacy technology does Monero use?',
    back: 'RingCT (ring signatures + Pedersen commitments) + stealth addresses + Bulletproofs for range proofs. No trusted setup.',
    tags: ['monero', 'ringct', 'stealth-addresses'],
  },
  {
    id: 'pp-03',
    chapter: 'ch24',
    category: 'definition',
    front: 'What is Penumbra?',
    back: 'A shielded DEX and payment network built on Cosmos IBC, using Groth16 proofs and a homomorphic value-based ledger model.',
    tags: ['penumbra', 'cosmos', 'shielded-dex'],
  },
  {
    id: 'pp-04',
    chapter: 'ch24',
    category: 'definition',
    front: 'What is Namada?',
    back: 'A proof-of-stake blockchain focused on multi-asset shielded transfers. Uses MASP (Multi-Asset Shielded Pool) — a Sapling extension for any asset.',
    tags: ['namada', 'masp', 'shielded-pool'],
  },
  {
    id: 'pp-05',
    chapter: 'ch24',
    category: 'definition',
    front: 'What are Silent Payments?',
    back: 'Bitcoin privacy scheme (BIP-352) where sender derives a unique address from recipient\'s public key — no address reuse, no interactive protocol.',
    tags: ['silent-payments', 'bitcoin', 'bip352'],
  },
  {
    id: 'pp-06',
    chapter: 'ch24',
    category: 'acronym',
    front: 'What does "MASP" stand for?',
    back: 'Multi-Asset Shielded Pool — Namada\'s extension of Zcash\'s Sapling to support multiple asset types in one unified privacy pool.',
    tags: ['masp', 'namada', 'zcash'],
  },
  {
    id: 'pp-07',
    chapter: 'ch24',
    category: 'definition',
    front: 'What is a stealth address?',
    back: 'A one-time address derived from the recipient\'s public key. Each payment goes to a unique address, preventing blockchain observers from linking transactions.',
    tags: ['stealth-address', 'privacy', 'monero'],
  },
  {
    id: 'pp-08',
    chapter: 'ch24',
    category: 'fact',
    front: 'What is the "Privacy is Normal" principle in private payments?',
    back: 'Privacy should be default (not opt-in) to build a large anonymity set — opt-in privacy reveals who values privacy, defeating the purpose.',
    tags: ['anonymity-set', 'privacy-design'],
  },
  {
    id: 'pp-09',
    chapter: 'ch24',
    category: 'fact',
    front: 'What is "address reuse" and why is it a privacy problem?',
    back: 'Sending multiple payments to the same address links them on-chain. Any observer can see the full transaction history of that address.',
    tags: ['address-reuse', 'privacy', 'linkability'],
  },
  {
    id: 'pp-10',
    chapter: 'ch24',
    category: 'definition',
    front: 'What is a nullifier in shielded payment systems?',
    back: 'A unique value derived from a note that is published when the note is spent — prevents double-spending without revealing which note was consumed.',
    tags: ['nullifier', 'zcash', 'double-spend'],
  },
  {
    id: 'pp-11',
    chapter: 'ch24',
    category: 'fact',
    front: 'What is "Tornado Cash" and why was it sanctioned?',
    back: 'An Ethereum mixing protocol using Groth16 proofs for anonymity. OFAC sanctioned it in 2022 — first ever sanctioning of an open-source smart contract.',
    tags: ['tornado-cash', 'ofac', 'mixer'],
  },
  {
    id: 'pp-12',
    chapter: 'ch24',
    category: 'definition',
    front: 'What is a coin join?',
    back: 'Bitcoin privacy technique where multiple users combine their UTXOs in one transaction, making it harder to trace individual payment flows.',
    tags: ['coinjoin', 'bitcoin', 'privacy'],
  },

  /* ===================== CH 2.5 — ZK Proof Systems ===================== */

  {
    id: 'zk-01',
    chapter: 'ch25',
    category: 'definition',
    front: 'What is Groth16?',
    back: 'The most efficient pairing-based zk-SNARK (2016). Constant-size proof (3 group elements), fast verification. Requires a circuit-specific trusted setup.',
    tags: ['groth16', 'snark', 'pairing'],
  },
  {
    id: 'zk-02',
    chapter: 'ch25',
    category: 'definition',
    front: 'What is PLONK?',
    back: 'A universal zk-SNARK with a universal (reusable) trusted setup. Uses polynomial commitments and a permutation argument. Slower than Groth16 but more flexible.',
    tags: ['plonk', 'universal', 'srs'],
  },
  {
    id: 'zk-03',
    chapter: 'ch25',
    category: 'definition',
    front: 'What is proof folding / Nova?',
    back: 'Nova (Kothapalli et al. 2022) is a recursive proof system using "folding" to accumulate many proof steps without recursion overhead. Uses relaxed R1CS.',
    tags: ['nova', 'folding', 'recursive'],
  },
  {
    id: 'zk-04',
    chapter: 'ch25',
    category: 'definition',
    front: 'What is Halo2?',
    back: 'Zcash\'s zk-SNARK framework using polynomial commitments (IPA) over Pasta curves. Enables recursive proofs without pairing — no trusted setup per circuit.',
    tags: ['halo2', 'zcash', 'ipa', 'recursive'],
  },
  {
    id: 'zk-05',
    chapter: 'ch25',
    category: 'definition',
    front: 'What is Plonky3?',
    back: 'A modular STARK framework by Polygon. Supports multiple hash functions and fields. Used in Polygon\'s zkEVM and other high-performance ZK systems.',
    tags: ['plonky3', 'stark', 'polygon'],
  },
  {
    id: 'zk-06',
    chapter: 'ch25',
    category: 'definition',
    front: 'What is Binius?',
    back: 'A SNARK over binary fields (GF(2^k)). Ultra-fast prover using binary arithmetic — avoids field-to-binary conversion overhead. Enables hardware acceleration.',
    tags: ['binius', 'binary-fields', 'snark'],
  },
  {
    id: 'zk-07',
    chapter: 'ch25',
    category: 'acronym',
    front: 'What is the difference between a SNARK and a STARK?',
    back: 'SNARK = Succinct Non-interactive ARgument of Knowledge (often needs trusted setup, small proofs). STARK = Scalable Transparent ARgument (no trusted setup, larger proofs, quantum-resistant).',
    tags: ['snark', 'stark', 'comparison'],
  },
  {
    id: 'zk-08',
    chapter: 'ch25',
    category: 'definition',
    front: 'What is a "trusted setup" in ZK proof systems?',
    back: 'A one-time ceremony generating public parameters (SRS). If the randomness ("toxic waste") is not destroyed, the system is compromised — fake proofs possible.',
    tags: ['trusted-setup', 'srs', 'toxic-waste'],
  },
  {
    id: 'zk-09',
    chapter: 'ch25',
    category: 'fact',
    front: 'What curves does Groth16 commonly use?',
    back: 'BN254 (aka alt_bn128) for Ethereum compatibility, and BLS12-381 for Zcash. Both are pairing-friendly elliptic curves with ~128-bit security.',
    tags: ['bn254', 'bls12-381', 'pairing-curves'],
  },
  {
    id: 'zk-10',
    chapter: 'ch25',
    category: 'definition',
    front: 'What is R1CS?',
    back: 'Rank-1 Constraint System — a way to express computations as matrix equations A·z * B·z = C·z. The standard circuit representation for Groth16 and PLONK.',
    tags: ['r1cs', 'circuit', 'constraints'],
  },
  {
    id: 'zk-11',
    chapter: 'ch25',
    category: 'definition',
    front: 'What is a polynomial commitment scheme?',
    back: 'A scheme where a prover commits to a polynomial and later proves evaluations at queried points. KZG (Kate) and IPA (inner-product argument) are two types.',
    tags: ['polynomial-commitment', 'kzg', 'ipa'],
  },
  {
    id: 'zk-12',
    chapter: 'ch25',
    category: 'fact',
    front: 'What is "zkLogin" in the context of Sui?',
    back: 'Mysten Labs\' protocol allowing Sui accounts to be controlled by OAuth JWT tokens (Google, Facebook). Uses Groth16 on BN254 via fastcrypto-zkp.',
    tags: ['zklogin', 'sui', 'jwt', 'oauth'],
  },
  {
    id: 'zk-13',
    chapter: 'ch25',
    category: 'definition',
    front: 'What is the Fiat-Shamir transform?',
    back: 'Converts an interactive proof (prover and verifier exchange messages) to non-interactive by replacing the verifier\'s random challenge with a hash output.',
    tags: ['fiat-shamir', 'non-interactive', 'random-oracle'],
  },
  {
    id: 'zk-14',
    chapter: 'ch25',
    category: 'definition',
    front: 'What is a zkEVM?',
    back: 'A zero-knowledge proof system that proves correct EVM execution. Enables succinct verification of Ethereum-compatible computation (e.g., Polygon, Scroll, zkSync).',
    tags: ['zkevm', 'ethereum', 'l2'],
  },
  {
    id: 'zk-15',
    chapter: 'ch25',
    category: 'fact',
    front: 'What does "soundness" mean in ZK proofs?',
    back: 'A cheating prover cannot convince a verifier of a false statement, except with negligible probability — the core security property of proof systems.',
    tags: ['soundness', 'zkp', 'security'],
  },

  /* ===================== CH 2.6 — MPC / FHE ===================== */

  {
    id: 'mpc-01',
    chapter: 'ch26',
    category: 'acronym',
    front: 'What does "MPC" stand for?',
    back: 'Multi-Party Computation — protocols where multiple parties jointly compute a function over their private inputs without revealing those inputs to each other.',
    tags: ['mpc', 'definition'],
  },
  {
    id: 'mpc-02',
    chapter: 'ch26',
    category: 'acronym',
    front: 'What does "FHE" stand for?',
    back: 'Fully Homomorphic Encryption — encryption that allows arbitrary computation on ciphertexts without decrypting them. Very slow but theoretically universal.',
    tags: ['fhe', 'definition', 'homomorphic'],
  },
  {
    id: 'mpc-03',
    chapter: 'ch26',
    category: 'definition',
    front: 'What is OpenFHE?',
    back: 'An open-source FHE library supporting CKKS, BFV, BGV, and FHEW/TFHE schemes. Used for prototyping homomorphic computations in research.',
    tags: ['openfhe', 'library', 'ckks'],
  },
  {
    id: 'mpc-04',
    chapter: 'ch26',
    category: 'definition',
    front: 'What is TFHE?',
    back: 'A fast FHE scheme optimized for Boolean gate evaluation. Each gate evaluation takes ~1ms on modern hardware. Used in Zama\'s concrete library.',
    tags: ['tfhe', 'fhe', 'boolean', 'zama'],
  },
  {
    id: 'mpc-05',
    chapter: 'ch26',
    category: 'definition',
    front: 'What is MP-SPDZ?',
    back: 'A framework for MPC protocols (SPDZ, MASCOT, etc.) supporting multiple security models (semi-honest, malicious). Standard research tool for MPC benchmarks.',
    tags: ['mp-spdz', 'mpc', 'spdz'],
  },
  {
    id: 'mpc-06',
    chapter: 'ch26',
    category: 'definition',
    front: 'What is FROST?',
    back: 'Flexible Round-Optimized Schnorr Threshold signatures — a t-of-n threshold signing protocol based on Schnorr. RFC 9591. Used for distributed key management.',
    tags: ['frost', 'threshold', 'schnorr', 'rfc9591'],
  },
  {
    id: 'mpc-07',
    chapter: 'ch26',
    category: 'acronym',
    front: 'What does "PSI" stand for in MPC?',
    back: 'Private Set Intersection — two parties compute the intersection of their sets without revealing non-intersecting elements to each other.',
    tags: ['psi', 'set-intersection', 'mpc'],
  },
  {
    id: 'mpc-08',
    chapter: 'ch26',
    category: 'definition',
    front: 'What is the CKKS scheme in FHE?',
    back: 'Cheon-Kim-Kim-Song — an FHE scheme supporting approximate arithmetic on real/complex numbers. Best for ML inference and statistical computations.',
    tags: ['ckks', 'fhe', 'approximate'],
  },
  {
    id: 'mpc-09',
    chapter: 'ch26',
    category: 'fact',
    front: 'What is "garbled circuits"?',
    back: 'A 2-party MPC technique (Yao 1986) where one party encrypts ("garbles") a circuit so the other evaluates it obliviously without learning intermediate values.',
    tags: ['garbled-circuits', 'yao', '2pc'],
  },
  {
    id: 'mpc-10',
    chapter: 'ch26',
    category: 'fact',
    front: 'What is the key bottleneck of FHE today?',
    back: 'Performance — FHE operations are 10^4 to 10^6x slower than plaintext equivalents. Active research into hardware acceleration (FPGAs, ASICs) aims to close this gap.',
    tags: ['fhe', 'performance', 'hardware'],
  },

  /* ===================== Rust ===================== */

  {
    id: 'rust-01',
    chapter: 'rust',
    category: 'definition',
    front: 'What is "ownership" in Rust?',
    back: 'Each value has exactly one owner. When the owner goes out of scope, the value is dropped. Enables memory safety without a garbage collector.',
    tags: ['ownership', 'rust', 'memory'],
  },
  {
    id: 'rust-02',
    chapter: 'rust',
    category: 'definition',
    front: 'What is a "lifetime" in Rust?',
    back: 'A named scope annotation (&\'a T) that tells the borrow checker how long a reference is valid. Prevents dangling references at compile time.',
    tags: ['lifetime', 'rust', 'borrow-checker'],
  },
  {
    id: 'rust-03',
    chapter: 'rust',
    category: 'fact',
    front: 'What crate does Mysten Labs use for cryptography in Sui?',
    back: 'fastcrypto — a unified trait-based crypto library wrapping Ed25519, BLS12-381, Secp256k1, Pedersen commitments, and Bulletproofs.',
    tags: ['fastcrypto', 'sui', 'mysten'],
  },
  {
    id: 'rust-04',
    chapter: 'rust',
    category: 'definition',
    front: 'What is the "arkworks" ecosystem in Rust?',
    back: 'A modular Rust library for ZK-SNARK development: curves, finite fields, R1CS constraints, Groth16, Marlin provers. Standard for academic ZK research in Rust.',
    tags: ['arkworks', 'rust', 'zkp'],
  },
  {
    id: 'rust-05',
    chapter: 'rust',
    category: 'definition',
    front: 'What is curve25519-dalek?',
    back: 'A Rust library for arithmetic on Curve25519 (Ed25519 signatures, X25519 key exchange) and Ristretto255. Constant-time by default.',
    tags: ['curve25519', 'dalek', 'ed25519', 'ristretto'],
  },
  {
    id: 'rust-06',
    chapter: 'rust',
    category: 'fact',
    front: 'What does the "zeroize" crate do in Rust?',
    back: 'Securely zeros memory on drop — prevents cryptographic secrets (keys, nonces) from persisting in RAM after use and being extracted via memory dumps.',
    tags: ['zeroize', 'rust', 'security'],
  },
  {
    id: 'rust-07',
    chapter: 'rust',
    category: 'definition',
    front: 'What is the "subtle" crate in Rust?',
    back: 'Provides constant-time comparisons and conditional operations to prevent timing side-channel attacks in cryptographic code.',
    tags: ['subtle', 'constant-time', 'side-channel'],
  },
  {
    id: 'rust-08',
    chapter: 'rust',
    category: 'definition',
    front: 'What is a Rust trait?',
    back: 'A collection of method signatures that types can implement — similar to interfaces in other languages. Enables polymorphism and generic programming.',
    tags: ['trait', 'rust', 'polymorphism'],
  },
  {
    id: 'rust-09',
    chapter: 'rust',
    category: 'fact',
    front: 'What is "thiserror" used for in Rust?',
    back: 'A derive macro for defining custom error types implementing std::error::Error — the standard pattern for library error handling in Rust.',
    tags: ['thiserror', 'error-handling', 'rust'],
  },
  {
    id: 'rust-10',
    chapter: 'rust',
    category: 'fact',
    front: 'What is "proptest" in Rust?',
    back: 'A property-based testing library — generates random inputs to find edge cases automatically. Essential for testing cryptographic invariants.',
    tags: ['proptest', 'testing', 'rust'],
  },
  {
    id: 'rust-11',
    chapter: 'rust',
    category: 'definition',
    front: 'What does "cargo-fuzz" do?',
    back: 'A fuzzing tool for Rust using libFuzzer. Finds panics and undefined behavior by feeding unexpected inputs. Used to harden cryptographic parsing code.',
    tags: ['fuzzing', 'cargo-fuzz', 'security'],
  },
  {
    id: 'rust-12',
    chapter: 'rust',
    category: 'fact',
    front: 'What is the Ristretto group in Rust crypto?',
    back: 'A prime-order group constructed from Curve25519 to avoid cofactor issues. Used in dalek for safe Diffie-Hellman and Pedersen commitments.',
    tags: ['ristretto', 'curve25519', 'group'],
  },
];
