/**
 * Acronym Lexicon — Maps acronyms to full names and short descriptions.
 * Used by study-guide.js for hover tooltips and the lexicon panel.
 */

window.LEXICON = {
  "ZKP": { full: "Zero-Knowledge Proof", desc: "Cryptographic proof that reveals nothing beyond the statement's truth" },
  "ZK": { full: "Zero-Knowledge", desc: "Property of revealing nothing beyond validity" },
  "TEE": { full: "Trusted Execution Environment", desc: "Hardware-isolated secure computation enclave" },
  "SGX": { full: "Software Guard Extensions", desc: "Intel's TEE implementation using CPU enclaves" },
  "TDX": { full: "Trust Domain Extensions", desc: "Intel's VM-level TEE, successor to SGX" },
  "SEV": { full: "Secure Encrypted Virtualization", desc: "AMD's VM-level TEE technology" },
  "SNARK": { full: "Succinct Non-interactive Argument of Knowledge", desc: "Compact ZK proof, constant-size, fast verification" },
  "STARK": { full: "Scalable Transparent Argument of Knowledge", desc: "ZK proof with no trusted setup, quantum-resistant" },
  "BBS+": { full: "Boneh-Boyen-Shacham+ Signature", desc: "Pairing-based multi-message signature enabling selective disclosure" },
  "CL": { full: "Camenisch-Lysyanskaya", desc: "RSA-based anonymous credential signature scheme" },
  "VC": { full: "Verifiable Credential", desc: "W3C standard for tamper-proof digital credentials" },
  "VP": { full: "Verifiable Presentation", desc: "Packaged set of VCs presented to a verifier" },
  "DID": { full: "Decentralized Identifier", desc: "Self-sovereign identifier resolved without central authority" },
  "SSI": { full: "Self-Sovereign Identity", desc: "Identity model where users control their own credentials" },
  "MPC": { full: "Multi-Party Computation", desc: "Protocol for joint computation on private inputs" },
  "OT": { full: "Oblivious Transfer", desc: "Protocol where receiver picks one of sender's messages without sender knowing which" },
  "FHE": { full: "Fully Homomorphic Encryption", desc: "Encryption allowing computation on ciphertexts" },
  "ORAM": { full: "Oblivious RAM", desc: "Memory access pattern hiding technique" },
  "R1CS": { full: "Rank-1 Constraint System", desc: "Arithmetic circuit representation for ZK proofs" },
  "QAP": { full: "Quadratic Arithmetic Program", desc: "Polynomial encoding of R1CS used in SNARKs" },
  "CRS": { full: "Common Reference String", desc: "Shared setup parameters for ZK proof systems" },
  "SRS": { full: "Structured Reference String", desc: "Universal setup parameters (PLONK)" },
  "KZG": { full: "Kate-Zaverucha-Goldberg", desc: "Polynomial commitment scheme used in PLONK" },
  "FRI": { full: "Fast Reed-Solomon IOP", desc: "Low-degree testing protocol used in STARKs" },
  "NTT": { full: "Number Theoretic Transform", desc: "FFT over finite fields, key for ZK proof performance" },
  "MSM": { full: "Multi-Scalar Multiplication", desc: "Batch EC point multiplication, ZK prover bottleneck" },
  "ECC": { full: "Elliptic Curve Cryptography", desc: "Public-key crypto based on elliptic curve discrete log" },
  "ECDLP": { full: "Elliptic Curve Discrete Logarithm Problem", desc: "Hard problem underlying ECC security" },
  "DLP": { full: "Discrete Logarithm Problem", desc: "Finding exponent given base and result in a group" },
  "CDH": { full: "Computational Diffie-Hellman", desc: "Hard problem: compute g^ab given g^a and g^b" },
  "DDH": { full: "Decisional Diffie-Hellman", desc: "Distinguishing g^ab from random given g^a, g^b" },
  "DBDH": { full: "Decisional Bilinear Diffie-Hellman", desc: "DDH analog in pairing-based cryptography" },
  "IBE": { full: "Identity-Based Encryption", desc: "Encryption where public key is an identity string" },
  "PRF": { full: "Pseudorandom Function", desc: "Deterministic function indistinguishable from random" },
  "LWE": { full: "Learning With Errors", desc: "Lattice-based hard problem, basis for post-quantum crypto" },
  "RLWE": { full: "Ring Learning With Errors", desc: "Structured LWE variant, more efficient" },
  "SIS": { full: "Short Integer Solution", desc: "Lattice problem: find short vector in lattice" },
  "PQ": { full: "Post-Quantum", desc: "Cryptography resistant to quantum computer attacks" },
  "NIST": { full: "National Institute of Standards and Technology", desc: "US standards body, led PQC standardization" },
  "PQC": { full: "Post-Quantum Cryptography", desc: "Crypto algorithms secure against quantum attacks" },
  "EPC": { full: "Enclave Page Cache", desc: "SGX encrypted memory region for enclaves" },
  "ECALL": { full: "Enclave Call", desc: "Entry point from untrusted code into SGX enclave" },
  "OCALL": { full: "Outside Call", desc: "Call from SGX enclave to untrusted code" },
  "DCAP": { full: "Data Center Attestation Primitives", desc: "SGX attestation without Intel online service" },
  "EPID": { full: "Enhanced Privacy ID", desc: "Intel group signature for anonymous attestation" },
  "IAS": { full: "Intel Attestation Service", desc: "Intel's online service for SGX quote verification" },
  "AES": { full: "Advanced Encryption Standard", desc: "Standard symmetric encryption (128/256-bit)" },
  "SHA": { full: "Secure Hash Algorithm", desc: "NIST hash function family (SHA-256, SHA-3)" },
  "BFT": { full: "Byzantine Fault Tolerant", desc: "Consensus tolerating malicious participants" },
  "UTXO": { full: "Unspent Transaction Output", desc: "Bitcoin-style transaction model" },
  "DeFi": { full: "Decentralized Finance", desc: "Financial services on blockchain without intermediaries" },
  "KYC": { full: "Know Your Customer", desc: "Identity verification for regulatory compliance" },
  "AML": { full: "Anti-Money Laundering", desc: "Regulations to prevent financial crime" },
  "FATF": { full: "Financial Action Task Force", desc: "International AML/CFT standards body" },
  "MiCA": { full: "Markets in Crypto-Assets", desc: "EU regulation for crypto-asset markets" },
  "eIDAS": { full: "Electronic Identification, Authentication and Trust Services", desc: "EU regulation for digital identity" },
  "ARF": { full: "Architecture Reference Framework", desc: "eIDAS 2.0 technical architecture specification" },
  "OFAC": { full: "Office of Foreign Assets Control", desc: "US sanctions enforcement agency" },
  "UC": { full: "Universal Composability", desc: "Security framework for composable protocol analysis" },
  "EUF-CMA": { full: "Existential Unforgeability under Chosen Message Attack", desc: "Standard signature security definition" },
  "IND-CCA": { full: "Indistinguishability under Chosen Ciphertext Attack", desc: "Standard encryption security definition" },
  "IND-CPA": { full: "Indistinguishability under Chosen Plaintext Attack", desc: "Weaker encryption security definition" },
  "HVZK": { full: "Honest-Verifier Zero-Knowledge", desc: "ZK property when verifier follows protocol honestly" },
  "NIZK": { full: "Non-Interactive Zero-Knowledge", desc: "ZK proof requiring no interaction" },
  "TPS": { full: "Transactions Per Second", desc: "Blockchain throughput metric" },
  "TtF": { full: "Time to Finality", desc: "Time until a transaction is irreversible" },
  "PSI": { full: "Private Set Intersection", desc: "MPC protocol to find common elements privately" },
  "VSS": { full: "Verifiable Secret Sharing", desc: "Secret sharing where dealer's honesty is verifiable" },
  "CRT": { full: "Chinese Remainder Theorem", desc: "Number theory theorem used for batching in FHE" },
  "SIMD": { full: "Single Instruction, Multiple Data", desc: "Parallel processing of multiple values" },
  "SDK": { full: "Software Development Kit", desc: "Developer tools and libraries" },
  "API": { full: "Application Programming Interface", desc: "Interface for software component interaction" },
  "VM": { full: "Virtual Machine", desc: "Software emulation of a computer system" },
  "SUI": { full: "Sui Network", desc: "Layer-1 blockchain by Mysten Labs with object-centric model" },
  "BLS": { full: "Boneh-Lynn-Shacham", desc: "Pairing-based signature scheme with aggregation" },
  "UTT": { full: "UnTraceable Transactions", desc: "Decentralized ecash with accountable privacy (Tomescu et al. 2022)" },
};
